/*
 * Whole-sortie fixed-backend parity harness.
 *
 * Drives the real flight loop — input_pumpEvents -> stepFlightModel ->
 * updateFrame — through a deterministic scripted sortie and hashes the
 * simulation state after every step, grouped like blackbox_diag:
 * flight / camera / objects / weapons / mission.
 *
 * The committed golden (tests/goldens/sortie_parity.trace) was generated by
 * this same source built at the pre-migration tag e28b9a4, so equal hashes
 * prove the migration series preserved fixed-backend behavior tick-for-tick.
 * A mismatch reports the first divergent tick and subsystem.
 *
 *   sortie_parity_tests                 compare against the committed golden
 *   sortie_parity_tests record <file>   write a fresh trace (run at the tag)
 *   sortie_parity_tests dump            print per-tick flight/mission fields
 *
 * The shared schedule/init/field readers live in sortie_harness.hpp;
 * modern_sortie_tests reuses them for the tolerance compare.
 */
#include "sortie_harness.hpp"

namespace {
using namespace sortie;

/* `fields <file>` records the named per-tick field snapshot that
 * modern_sortie_tests compares against with tolerances. */
int recordFields(const char *path) {
    std::ofstream trace(path, std::ios::binary | std::ios::trunc);
    require(trace.good(), "cannot open field trace output");
    trace << "sortie_fields_trace 1 seed " << kSeed << " ticks " << kSortieTicks << "\n";
    for (int tick = 0; tick < kSortieTicks; ++tick) {
        runTick(tick);
        trace << tick;
        for (const auto &f : snapFields()) trace << ' ' << f.first << '=' << f.second;
        trace << '\n';
        require(trace.good(), "field trace write failed");
    }
    std::fprintf(stderr, "recorded %d field ticks to %s\n", kSortieTicks, path);
    return 0;
}

int runSortie(const char *path, bool record, bool dump) {
    std::ifstream golden;
    std::ofstream trace;
    if (record) {
        trace.open(path, std::ios::binary | std::ios::trunc);
        require(trace.good(), "cannot open trace output");
        trace << "sortie_parity_trace 1 seed " << kSeed << " ticks " << kSortieTicks << "\n";
    } else if (!dump) {
        golden.open(path, std::ios::binary);
        require(golden.good(), "cannot open golden trace (regenerate with 'record')");
        std::string header;
        std::getline(golden, header);
        require(header.rfind("sortie_parity_trace 1", 0) == 0, "golden trace header mismatch");
    }

    std::uint32_t flightFold = 0, objectsFold = 0;
    int divergedTick = -1;
    for (int tick = 0; tick < kSortieTicks; ++tick) {
        runTick(tick);

        const std::uint32_t flight = hashFlight();
        const std::uint32_t camera = hashCamera();
        const std::uint32_t objects = hashObjects();
        const std::uint32_t weapons = hashWeapons();
        const std::uint32_t mission = hashMission();
        flightFold ^= flight;
        objectsFold ^= objects;

        if (record) {
            trace << tick << ' ';
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%08x %08x %08x %08x %08x\n",
                          (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            trace << buf;
        } else if (dump) {
            std::printf("%d ", tick);
            dumpFlight(readFlight());
            std::printf("   ");
            dumpMission();
        } else {
            std::string line;
            require(std::getline(golden, line).good(), "golden trace ended early");
            char expected[64];
            std::snprintf(expected, sizeof(expected), "%d %08x %08x %08x %08x %08x",
                          tick, (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            if (line != expected && divergedTick < 0) {
                divergedTick = tick;
                std::fprintf(stderr, "first divergence at tick %d\n  got:      %s\n  expected: %s\n",
                             tick, expected, line.c_str());
                dumpFlight(readFlight());
            }
        }
    }
    /* Guard against a degenerate run (e.g. the sim never advanced). */
    require(flightFold != 0 || objectsFold != 0, "sortie produced an empty state stream");
    if (record) {
        require(trace.good(), "trace write failed");
        std::fprintf(stderr, "recorded %d ticks to %s\n", kSortieTicks, path);
    } else if (!dump) {
        require(divergedTick < 0, "sortie state diverged from the e28b9a4 golden");
        std::string extra;
        require(!std::getline(golden, extra).good(), "golden trace has extra ticks");
    }
    return 0;
}
}

int main(int argc, char **argv) {
    const bool record = argc == 3 && std::string(argv[1]) == "record";
    const bool fields = argc == 3 && std::string(argv[1]) == "fields";
    const bool dump = argc >= 2 && std::string(argv[1]) == "dump";
    require(record || fields || dump || argc == 1,
            "usage: sortie_parity_tests [record <out.trace> | fields <out.trace> | dump]");
    initSortie();
    int result = 0;
    if (fields) {
        result = recordFields(argv[2]);
    } else {
        const char *path = record ? argv[2] : F15_GOLDEN_DIR "/sortie_parity.trace";
        result = runSortie(path, record, dump);
    }
    teardown();
    if (!record && !fields && !dump)
        std::puts("sortie parity: 660 ticks match the e28b9a4 golden");
    return result;
}
