/*
 * Whole-sortie fixed-backend parity harness.
 *
 * Drives the real flight loop — input_pumpEvents -> stepFlightModel ->
 * updateFrame — through a deterministic scripted sortie and hashes the
 * simulation state after every step, grouped like blackbox_diag:
 * flight / camera / objects / weapons / mission.
 *
 * The committed golden (tests/goldens/sortie_parity.trace) was generated by
 * this same source built at the pre-migration tag e28b9a4, so equal hashes
 * prove the migration series preserved fixed-backend behavior tick-for-tick.
 * A mismatch reports the first divergent tick and subsystem.
 *
 *   sortie_parity_tests                 compare against the committed golden
 *   sortie_parity_tests record <file>   write a fresh trace (run at the tag)
 *
 * Determinism: no wall-clock input reaches the sim. The timer IRQ is never
 * installed (timerPump no-ops), gameRand() is seeded, discrete commands go
 * through SDL key events into the BIOS ring, and stick bytes are written to
 * g_joyRawX/Y after each pump (no joystick is attached, so stepFlightModel
 * scales g_joyRaw through the keyboard curve — the same path blackbox
 * replays axes through).
 */
#include "headless.h"

#include "math/legacy_airspeed.hpp"
#include "math/legacy_altitude.hpp"
#include "math/legacy_rotation.hpp"
#include "math/legacy_horizontal.hpp"
#include "math/legacy_map.hpp"
#include "math/legacy_propulsion.hpp"
#include "math/legacy_flight_control.hpp"
#include "egdata.h"
#include "egflight.h"
#include "egkeys.h"
#include "comm.h"
#include "input.h"
#include "strand.h"
#include "gfx.h"
#include "egcode.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <string>

void stepFlightModel();
void updateFrame();
void rebuildOrientation();

namespace {
using namespace f15::math;

constexpr int kSortieTicks = 660;
constexpr std::uint32_t kSeed = 0x51e7u;

/* g_joyRaw byte range used by controls_applyAxes (0x26/0xda off-centre). */
enum : std::int16_t {
    kStickMin = 0x26,
    kStickCenter = 0x80,
    kStickMax = 0xda,
};

void require(bool ok, const char *message) {
    if (!ok) { std::fprintf(stderr, "sortie_parity: %s\n", message); std::exit(1); }
}

void pushKey(SDL_Scancode scancode, SDL_Keycode key) {
    SDL_Event ev{};
    ev.type = SDL_EVENT_KEY_DOWN;
    ev.key.scancode = scancode;
    ev.key.key = key;
    SDL_PushEvent(&ev);
}

/* Discrete cockpit commands for this tick, pushed before the pump so the
 * translated BIOS word reaches the key ring stepFlightModel drains. */
void pushScheduleKeys(int tick) {
    if (tick < 40) pushKey(SDL_SCANCODE_EQUALS, SDLK_EQUALS);      // throttle ramp
    if (tick == 45) pushKey(SDL_SCANCODE_G, SDLK_G);              // gear up
    if (tick == 280) for (int i = 0; i < 16; ++i)                 // throttle cut
        pushKey(SDL_SCANCODE_MINUS, SDLK_MINUS);
    if (tick == 390) pushKey(SDL_SCANCODE_W, SDLK_W);             // weapon select
    if (tick == 392 || tick == 394) pushKey(SDL_SCANCODE_RETURN, SDLK_RETURN);   // fire missile
    if (tick == 400) pushKey(SDL_SCANCODE_BACKSPACE, SDLK_BACKSPACE);          // guns
    if (tick == 540) {
        pushKey(SDL_SCANCODE_G, SDLK_G);                          // gear down
        pushKey(SDL_SCANCODE_B, SDLK_B);                          // airbrake
    }
    if (tick >= 560 && (tick & 7) == 0) pushKey(SDL_SCANCODE_MINUS, SDLK_MINUS);
    if (tick == 600) pushKey(SDL_SCANCODE_P, SDLK_P);             // autopilot on
}

/* Stick position for this tick; written after input_pumpEvents because the
 * pump's updateStick() rewrites g_joyRawX/Y from (absent) keyboard arrows. */
void applyScheduleStick(int tick) {
    std::int16_t roll = kStickCenter, pitch = kStickCenter;
    if (tick >= 60 && tick < 120) pitch = kStickMin;              // climb
    else if (tick >= 120 && tick < 200) roll = kStickMax;         // banked turn
    else if (tick >= 200 && tick < 280) roll = kStickMin;         // counter-turn
    else if (tick >= 280 && tick < 340) pitch = kStickMax;        // push over
    else if (tick >= 340 && tick < 380) pitch = 0x40;             // pull -> stall
    else if (tick >= 420 && tick < 540) roll = 0xa0;              // sustained turn
    else if (tick >= 540 && tick < 640) pitch = 0x90;             // descend
    g_joyRawX = (uint8)roll;
    g_joyRawY = (uint8)pitch;
}

/* Same FNV-1a-style byte mix as blackbox_diag (kept local: the diag hashers
 * are static internals, and an identical mix makes traces comparable). */
std::uint32_t hashAdd(std::uint32_t hash, std::uint32_t value) {
    for (int i = 0; i < 4; ++i) {
        hash ^= value & 0xffu;
        hash *= 16777619u;
        value >>= 8;
    }
    return hash;
}

struct FlightFields {
    std::uint32_t fineX, fineY;
    std::uint32_t viewZ, head, pitch, roll, speed, altitude;
    std::uint32_t knots, corner, stall, rollIn, pitchIn, lift, trim;
    std::uint32_t thrust, setThrust, fuel, gees, viewX, viewY;
    std::uint32_t apEngaged, apAlt, planeFlags, gearArmed, eject, gunHits, damage;
};

FlightFields readFlight() {
    FlightFields f{};
    f.fineX = (std::uint32_t)legacy::fineUnits(g_ViewX);
    f.fineY = (std::uint32_t)legacy::fineUnits(g_ViewY);
    f.viewZ = (std::uint16_t)g_viewZ;
    f.head = (std::uint16_t)legacy::signedAngle(g_ourHead);
    f.pitch = (std::uint16_t)legacy::signedAngle(g_ourPitch);
    f.roll = (std::uint16_t)legacy::signedAngle(g_ourRoll);
    f.speed = (std::uint32_t)legacy::speedUnits(g_velocity);
    f.altitude = legacy::altitudeUnits(g_altitude);
    f.knots = (std::uint16_t)g_knots;
    f.corner = (std::uint16_t)g_cornerSpeed;
    f.stall = (std::uint32_t)legacy::Airspeeds::stall(g_stallSpeed);
    f.rollIn = (std::uint32_t)legacy::rollInput(g_rollInput);
    f.pitchIn = (std::uint32_t)legacy::pitchInput(g_pitchInput);
    f.lift = (std::uint16_t)legacy::signedAngle(g_liftForce);
    f.trim = (std::uint16_t)legacy::signedAngle(g_rollPitchTrim);
    f.thrust = (std::uint16_t)legacy::thrustUnits(g_thrust);
    f.setThrust = (std::uint16_t)g_setThrust;
    f.fuel = (std::uint16_t)g_fuelRemaining;
    f.gees = (std::uint32_t)legacy::loadSixteenths(g_gees);
    f.viewX = (std::uint16_t)g_viewX_;
    f.viewY = (std::uint16_t)g_viewY_;
    f.apEngaged = (std::uint16_t)g_autopilotEngaged;
    f.apAlt = (std::uint32_t)legacy::Altitudes::render(g_autopilotAltitude);
    f.planeFlags = (std::uint16_t)g_playerPlaneFlags;
    f.gearArmed = (std::uint16_t)g_gearDownArmed;
    f.eject = (std::uint16_t)g_ejectState;
    f.gunHits = (std::uint16_t)g_gunHits;
    f.damage = (std::uint16_t)g_damageTakenFlag;
    return f;
}

void dumpFlight(const FlightFields &f) {
    std::printf("fineX=%u fineY=%u viewZ=%u head=%u pitch=%u roll=%u speed=%u alt=%u\n"
                "knots=%u corner=%u stall=%u rollIn=%u pitchIn=%u lift=%u trim=%u\n"
                "thrust=%u setThrust=%u fuel=%u gees=%u viewX=%u viewY=%u ap=%u apAlt=%u\n"
                "flags=%u gear=%u eject=%u gunHits=%u damage=%u\n",
                f.fineX, f.fineY, f.viewZ, f.head, f.pitch, f.roll, f.speed, f.altitude,
                f.knots, f.corner, f.stall, f.rollIn, f.pitchIn, f.lift, f.trim,
                f.thrust, f.setThrust, f.fuel, f.gees, f.viewX, f.viewY, f.apEngaged, f.apAlt,
                f.planeFlags, f.gearArmed, f.eject, f.gunHits, f.damage);
}

std::uint32_t hashFlight() {
    const FlightFields &f = readFlight();
    std::uint32_t h = 0x811c9dc5u;
    for (std::uint32_t v : {f.fineX, f.fineY, f.viewZ, f.head, f.pitch, f.roll, f.speed,
                            f.altitude, f.knots, f.corner, f.stall, f.rollIn, f.pitchIn,
                            f.lift, f.trim, f.thrust, f.setThrust, f.fuel, f.gees,
                            f.viewX, f.viewY, f.apEngaged, f.apAlt, f.planeFlags,
                            f.gearArmed, f.eject, f.gunHits, f.damage})
        h = hashAdd(h, v);
    return h;
}

std::uint32_t hashCamera() {
    std::uint32_t h = 0x811c9dc5u;
    h = hashAdd(h, (std::uint32_t)g_camEyeX);
    h = hashAdd(h, (std::uint32_t)g_camEyeY);
    h = hashAdd(h, (std::uint16_t)g_camEyeZ);
    h = hashAdd(h, (std::uint16_t)g_camEyeFracX);
    h = hashAdd(h, (std::uint16_t)g_camEyeFracY);
    h = hashAdd(h, (std::uint16_t)g_camEyeFracZ);
    h = hashAdd(h, (std::uint16_t)g_viewMode);
    return h;
}

std::uint32_t hashObjects() {
    std::uint32_t h = 0x811c9dc5u;
    for (int i = 0; i < 8; ++i) {
        const auto &p = g_planeTable.planes[i];
        h = hashAdd(h, p.mapX);
        h = hashAdd(h, p.mapY);
        h = hashAdd(h, (std::uint16_t)p.active);
        h = hashAdd(h, (std::uint16_t)p.flags);
        h = hashAdd(h, (std::uint16_t)p.alertLevel);
        h = hashAdd(h, (std::uint16_t)p.threatTimer);
    }
    for (int i = 0; i < 8; ++i) {
        const auto &o = g_simObjects[i];
        h = hashAdd(h, o.posX);
        h = hashAdd(h, o.posY);
        h = hashAdd(h, (std::uint32_t)o.worldX);
        h = hashAdd(h, (std::uint32_t)o.worldY);
        h = hashAdd(h, (std::uint16_t)o.alt);
        h = hashAdd(h, (std::uint16_t)o.speed);
        h = hashAdd(h, o.flags.w);
        h = hashAdd(h, (std::uint16_t)o.heading.w);
    }
    for (int i = 0; i < 8; ++i) {
        h = hashAdd(h, (std::uint32_t)legacy::fineWord(bulletTracks[i].posX));
        h = hashAdd(h, (std::uint32_t)legacy::fineWord(bulletTracks[i].posY));
        h = hashAdd(h, (std::uint32_t)(std::int32_t)bulletTracks[i].alt);
    }
    return h;
}

std::uint32_t hashWeapons() {
    std::uint32_t h = 0x811c9dc5u;
    for (int i = 0; i < 12; ++i) {
        const auto &w = g_projectiles[i];
        h = hashAdd(h, w.mapX);
        h = hashAdd(h, w.mapY);
        h = hashAdd(h, (std::uint16_t)w.alt);
        h = hashAdd(h, (std::uint16_t)w.ttl);
        h = hashAdd(h, (std::uint16_t)w.speed);
        h = hashAdd(h, (std::uint16_t)w.targetRef);
        h = hashAdd(h, (std::uint16_t)w.weaponIdx);
    }
    h = hashAdd(h, (std::uint16_t)g_bulletTrackCount);
    return h;
}

std::uint32_t hashMission() {
    std::uint32_t h = 0x811c9dc5u;
    h = hashAdd(h, (std::uint16_t)g_missionStatus);
    h = hashAdd(h, (std::uint16_t)g_landingTimer);
    h = hashAdd(h, (std::uint16_t)g_missionTick);
    h = hashAdd(h, (std::uint16_t)g_nearestThreatRange);
    h = hashAdd(h, (std::uint16_t)g_targetRange);
    h = hashAdd(h, (std::uint16_t)g_targetBearing);
    h = hashAdd(h, (std::uint16_t)g_northSouthSign);
    h = hashAdd(h, (std::uint16_t)g_missionEndedFlag[0]);
    h = hashAdd(h, (std::uint16_t)(commData ? commData->landingType : 0));
    h = hashAdd(h, (std::uint16_t)g_inLandingCorridor);
    h = hashAdd(h, (std::uint16_t)g_closestThreatIndex);
    h = hashAdd(h, (std::uint16_t)g_directorEventDeadline);
    h = hashAdd(h, (std::uint16_t)g_slowMotionMode);
    return h;
}

void dumpMission() {
    std::printf("mstatus=%d landT=%d mtick=%d nearR=%d tgtR=%d tgtB=%d ns=%d ended=%d landT2=%d corr=%d threat=%d dirDl=%d slow=%d apEng=%d\n",
                (int)g_missionStatus, (int)g_landingTimer, (int)g_missionTick,
                (int)g_nearestThreatRange, (int)g_targetRange, (int)g_targetBearing,
                (int)g_northSouthSign, (int)g_missionEndedFlag[0],
                commData ? (int)commData->landingType : -1, (int)g_inLandingCorridor,
                (int)g_closestThreatIndex, (int)g_directorEventDeadline,
                (int)g_slowMotionMode, (int)g_autopilotEngaged);
}

void initSortie() {
    test_headless_init();
    require(SDL_Init(SDL_INIT_GAMEPAD), "initialize SDL events");
    input_setMode(INPUT_MODE_FLIGHT);
    input_setJoystickSetup(false);
    SDL_Event focus{};
    focus.type = SDL_EVENT_WINDOW_FOCUS_GAINED;
    require(SDL_PushEvent(&focus), "focus flight input");
    input_pumpEvents();

    gfx_videoInit();
    gfx_setMode13();
    setupInstrumentLayoutFar();

    /* Static: gameData/commData must stay valid after initSortie returns. */
    static Game game{};
    static GameComm comm{};
    gameData = &game;
    commData = &comm;
    game.difficulty = 2;
    game.unk4 = 2;
    /* Non-empty loadout so the scheduled fire keys reach fireMissile(): the
     * mission-init block copies these into missleSpec[].ammo. */
    for (int i = 0; i < 3; ++i) {
        comm.weaponType[i] = (uint16)(i + 1);
        comm.weaponCount[i] = 4;
    }

    gameSrand(kSeed);

    g_initPhase = 1;               /* first updateFrame runs mission init */
    g_frameRateScaling = 15;
    frameTick = 1;
    /* seedRng() (inside initFrameRandom, mission init) clock-seeds unless input
     * is disabled; pin the deterministic path for the init tick, then enable. */
    g_inputDisabled = 1;
    g_rngSeed = (int16)kSeed;
    g_thrust = legacy::thrustFromUnits(35);
    g_setThrust = 5;
    g_fuelRemaining = 9000;
    g_viewZ = 4000;
    g_groundAltitude = 0;
    g_altitude = legacy::altitudeFromUnits(4000);
    g_velocity = legacy::speedFromUnits(8100);
    g_knots = 300;
    g_playerPlaneFlags = 0;        /* gear down on the runway */
    g_gearDownArmed = 1;
    g_cornerSpeed = 100;
    g_kbdSensitivity = 2;
    g_gunHits = g_hudVisible = 0;
    g_ejectState = g_autoCrashDive = g_currentWeaponType = 0;
    g_autopilotEngaged = 0;
    g_autopilotAltitude = {};
    g_missionTick = 0;
    g_waypointBearing = 0;
    waypointIndex = 1;
    g_ViewX = legacy::viewX(5000);
    g_ViewY = legacy::viewY(-5000);
    g_ourHead = legacy::angleFromWord(4000);
    g_ourPitch = g_ourRoll = {};
    g_stallSpeed = {};
    g_liftForce = g_rollPitchTrim = {};
    g_orientationDirty = g_rotationCounter = g_rollWasNonzero = 0;
    g_viewX_ = 5000;
    g_viewY_ = 60000;

    /* A few seeded contacts so threat/targeting/object paths engage. */
    g_planeCount = 12;
    /* No mission assets are loaded: point every name-table slot at an empty
     * string so placeString() (spawnEnemyAircraft, waypoints) stays valid. */
    g_stringPool[0] = '\0';
    for (int i = 0; i < MODEL_SLOT_CAPACITY; ++i) g_targetNameTable[i] = g_stringPool;
    g_groundUnitCount = 4;
    g_planeTable.planes[1].mapX = 12000;
    g_planeTable.planes[1].mapY = 20000;
    g_planeTable.planes[1].active = 1;
    g_planeTable.planes[1].flags = 0x100;
    g_planeTable.planes[2].mapX = 40000;
    g_planeTable.planes[2].mapY = 10000;
    g_planeTable.planes[2].active = 1;
    g_planeTable.planes[2].flags = 0x200;
    g_planeTable.planes[3].mapX = 8000;
    g_planeTable.planes[3].mapY = 40000;
    g_planeTable.planes[3].active = 1;
    g_planeTable.planes[3].flags = 0x100;
    for (int i = 0; i < 4; ++i) {
        g_simObjects[i].posX = (uint16)(9000 + i * 4000);
        g_simObjects[i].posY = (uint16)(15000 + i * 3000);
        g_simObjects[i].alt = (int16)(200 + i * 50);
        g_simObjects[i].heading.w = (int16)(i * 8192);
        g_simObjects[i].speed = 40;
        g_simObjects[i].spec = 1;
        g_simObjects[i].flags.w = 0x100;
    }

    rebuildOrientation();
}

void teardown() {
    gameData = nullptr;
    commData = nullptr;
    gfx_videoShutdown();
    SDL_Quit();
}

int runSortie(const char *path, bool record, bool dump) {
    std::ifstream golden;
    std::ofstream trace;
    if (record) {
        trace.open(path, std::ios::binary | std::ios::trunc);
        require(trace.good(), "cannot open trace output");
        trace << "sortie_parity_trace 1 seed " << kSeed << " ticks " << kSortieTicks << "\n";
    } else if (!dump) {
        golden.open(path, std::ios::binary);
        require(golden.good(), "cannot open golden trace (regenerate with 'record')");
        std::string header;
        std::getline(golden, header);
        require(header.rfind("sortie_parity_trace 1", 0) == 0, "golden trace header mismatch");
    }

    std::uint32_t flightFold = 0, objectsFold = 0;
    int divergedTick = -1;
    for (int tick = 0; tick < kSortieTicks; ++tick) {
        pushScheduleKeys(tick);
        input_pumpEvents();
        applyScheduleStick(tick);
        stepFlightModel();
        updateFrame();
        /* Mission init ran on tick 0 (deterministic seed via g_inputDisabled);
         * enable the scripted inputs from here on. */
        if (tick == 0) g_inputDisabled = 0;

        const std::uint32_t flight = hashFlight();
        const std::uint32_t camera = hashCamera();
        const std::uint32_t objects = hashObjects();
        const std::uint32_t weapons = hashWeapons();
        const std::uint32_t mission = hashMission();
        flightFold ^= flight;
        objectsFold ^= objects;

        if (record) {
            trace << tick << ' ';
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%08x %08x %08x %08x %08x\n",
                          (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            trace << buf;
        } else if (dump) {
            std::printf("%d ", tick);
            dumpFlight(readFlight());
            std::printf("   ");
            dumpMission();
        } else {
            std::string line;
            require(std::getline(golden, line).good(), "golden trace ended early");
            char expected[64];
            std::snprintf(expected, sizeof(expected), "%d %08x %08x %08x %08x %08x",
                          tick, (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            if (line != expected && divergedTick < 0) {
                divergedTick = tick;
                std::fprintf(stderr, "first divergence at tick %d\n  got:      %s\n  expected: %s\n",
                             tick, expected, line.c_str());
                dumpFlight(readFlight());
            }
        }
    }
    /* Guard against a degenerate run (e.g. the sim never advanced). */
    require(flightFold != 0 || objectsFold != 0, "sortie produced an empty state stream");
    if (record) {
        require(trace.good(), "trace write failed");
        std::fprintf(stderr, "recorded %d ticks to %s\n", kSortieTicks, path);
    } else if (!dump) {
        require(divergedTick < 0, "sortie state diverged from the e28b9a4 golden");
        std::string extra;
        require(!std::getline(golden, extra).good(), "golden trace has extra ticks");
    }
    return 0;
}
}

int main(int argc, char **argv) {
    const bool record = argc == 3 && std::string(argv[1]) == "record";
    const bool dump = argc >= 2 && std::string(argv[1]) == "dump";
    const char *path = record ? argv[2] : F15_GOLDEN_DIR "/sortie_parity.trace";
    require(record || dump || argc == 1,
            "usage: sortie_parity_tests [record <out.trace> | dump]");
    initSortie();
    const int result = runSortie(path, record, dump);
    teardown();
    if (!record && !dump) std::puts("sortie parity: 660 ticks match the e28b9a4 golden");
    return result;
}
