/*
 * Whole-sortie fixed-backend parity harness.
 *
 * Drives the real flight loop — input_pumpEvents -> stepFlightModel ->
 * updateFrame — through a deterministic scripted sortie and hashes the
 * simulation state after every step, grouped like blackbox_diag:
 * flight / camera / objects / weapons / mission.
 *
 * The committed golden (tests/goldens/sortie_parity.trace) was generated by
 * this same source built at the pre-migration tag e28b9a4, so equal hashes
 * prove the migration series preserved fixed-backend behavior tick-for-tick.
 * A mismatch reports the first divergent tick and subsystem.
 *
 * The --loop profile drives a sustained stick pull through the pole band via
 * a virtual joystick (sortie_harness.hpp explains why byte writes cannot
 * reach the sim). Its golden tests/goldens/sortie_loop_parity.trace was
 * recorded at HEAD: the profile exercises the post-tag pole-fold fix, so a
 * tag recording would pin the original trap instead of the fixed behavior.
 * The loop run also asserts the stick actually reached the sim.
 *
 *   sortie_parity_tests                 compare against the committed golden
 *   sortie_parity_tests record <file>   write a fresh trace (run at the tag)
 *   sortie_parity_tests dump            print per-tick flight/mission fields
 *   (append --loop for the loop profile: sortie_loop_parity.trace,
 *    --combat for the mission-import profile: sortie_combat_parity.trace,
 *    --land for the recovery/landing profile: sortie_land_parity.trace,
 *    --stick for the real-stick sortie: sortie_stick_parity.trace — the only
 *    profile whose golden is a true pre-migration oracle for live stick
 *    input, recorded on e28b9a4 via a virtual joystick)
 *
 * The shared schedule/init/field readers live in sortie_harness.hpp;
 * modern_sortie_tests reuses them for the tolerance compare.
 */
#include "sortie_harness.hpp"

namespace {
using namespace sortie;

/* `fields <file>` records the named per-tick field snapshot that
 * modern_sortie_tests compares against with tolerances. */
int recordFields(const char *path, Profile profile) {
    const int ticks = ticksForProfile(profile);
    std::ofstream trace(path, std::ios::binary | std::ios::trunc);
    require(trace.good(), "cannot open field trace output");
    trace << "sortie_fields_trace 1 seed " << kSeed << " ticks " << ticks << "\n";
    for (int tick = 0; tick < ticks; ++tick) {
        runTick(tick, profile);
        trace << tick;
        for (const auto &f : snapFields()) trace << ' ' << f.first << '=' << f.second;
        trace << '\n';
        require(trace.good(), "field trace write failed");
    }
    std::fprintf(stderr, "recorded %d field ticks to %s\n", ticks, path);
    return 0;
}

int runSortie(const char *path, bool record, bool dump, Profile profile) {
    std::ifstream golden;
    std::ofstream trace;
    const int ticks = ticksForProfile(profile);
    if (record) {
        trace.open(path, std::ios::binary | std::ios::trunc);
        require(trace.good(), "cannot open trace output");
        trace << "sortie_parity_trace 1 seed " << kSeed << " ticks " << ticks << "\n";
    } else if (!dump) {
        golden.open(path, std::ios::binary);
        require(golden.good(), "cannot open golden trace (regenerate with 'record')");
        std::string header;
        std::getline(golden, header);
        require(header.rfind("sortie_parity_trace 1", 0) == 0, "golden trace header mismatch");
    }

    std::uint32_t flightFold = 0, objectsFold = 0;
    int divergedTick = -1;
    LoopCheck loop;
    CombatCheck combat;
    StickCheck stick;
    LandingCheck land;
    BoundaryCheck boundary;
    StallCheck stall;
    for (int tick = 0; tick < ticks; ++tick) {
        runTick(tick, profile);
        if (profile == Profile::kLoop) loopObserve(loop, tick);
        if (profile == Profile::kCombat) combatObserve(combat, tick);
        if (profile == Profile::kStick) stickObserve(stick, tick);
        if (profile == Profile::kLand) landingObserve(land, tick);
        if (profile == Profile::kWrap) boundaryObserve(boundary, tick);
        if (profile == Profile::kStall) stallObserve(stall, tick);

        const std::uint32_t flight = hashFlight();
        const std::uint32_t camera = hashCamera();
        const std::uint32_t objects = hashObjects();
        const std::uint32_t weapons = hashWeapons();
        const std::uint32_t mission = hashMission();
        flightFold ^= flight;
        objectsFold ^= objects;

        if (record) {
            trace << tick << ' ';
            char buf[64];
            std::snprintf(buf, sizeof(buf), "%08x %08x %08x %08x %08x\n",
                          (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            trace << buf;
        } else if (dump) {
            std::printf("%d ", tick);
            dumpFlight(readFlight());
            std::printf("   ");
            dumpMission();
        } else {
            std::string line;
            require(std::getline(golden, line).good(), "golden trace ended early");
            char expected[64];
            std::snprintf(expected, sizeof(expected), "%d %08x %08x %08x %08x %08x",
                          tick, (unsigned)flight, (unsigned)camera, (unsigned)objects,
                          (unsigned)weapons, (unsigned)mission);
            if (line != expected && divergedTick < 0) {
                divergedTick = tick;
                std::fprintf(stderr, "first divergence at tick %d\n  got:      %s\n  expected: %s\n",
                             tick, expected, line.c_str());
                dumpFlight(readFlight());
            }
        }
    }
    /* Guard against a degenerate run (e.g. the sim never advanced). */
    require(flightFold != 0 || objectsFold != 0, "sortie produced an empty state stream");
    if (profile == Profile::kLoop) loopRequire(loop);
    if (profile == Profile::kStick) stickRequire(stick);
    if (profile == Profile::kCombat) {
        combatRequire(combat);
        verifyWorldExport();
    }
    if (profile == Profile::kLand) {
        landingRequire(land);
        verifyWorldExport();
    }
    if (profile == Profile::kWrap) boundaryRequire(boundary);
    if (profile == Profile::kStall) stallRequire(stall);
    if (record) {
        require(trace.good(), "trace write failed");
        std::fprintf(stderr, "recorded %d ticks to %s\n", ticks, path);
    } else if (!dump) {
        require(divergedTick < 0, "sortie state diverged from the golden trace");
        std::string extra;
        require(!std::getline(golden, extra).good(), "golden trace has extra ticks");
    }
    return 0;
}
}

int main(int argc, char **argv) {
    const bool loop = argc >= 2 && std::string(argv[argc - 1]) == "--loop";
    if (loop) --argc;
    const bool combat = argc >= 2 && std::string(argv[argc - 1]) == "--combat";
    if (combat) --argc;
    const bool stick = argc >= 2 && std::string(argv[argc - 1]) == "--stick";
    if (stick) --argc;
    const bool land = argc >= 2 && std::string(argv[argc - 1]) == "--land";
    if (land) --argc;
    const bool wrap = argc >= 2 && std::string(argv[argc - 1]) == "--wrap";
    if (wrap) --argc;
    const bool stall = argc >= 2 && std::string(argv[argc - 1]) == "--stall";
    if (stall) --argc;
    const bool record = argc == 3 && std::string(argv[1]) == "record";
    const bool fields = argc == 3 && std::string(argv[1]) == "fields";
    const bool dump = argc >= 2 && std::string(argv[1]) == "dump";
    require(record || fields || dump || argc == 1,
            "usage: sortie_parity_tests [record <out.trace> | fields <out.trace> | dump] [--loop | --combat | --stick | --land | --wrap | --stall]");
    const Profile profile = loop ? Profile::kLoop
                               : combat ? Profile::kCombat
                                        : stick ? Profile::kStick
                                                : land ? Profile::kLand
                                                       : wrap ? Profile::kWrap
                                                              : stall ? Profile::kStall : Profile::kSortie;
    initSortie(profile);
    int result = 0;
    if (fields) {
        result = recordFields(argv[2], profile);
    } else {
        const char *path = record ? argv[2]
            : (loop ? F15_GOLDEN_DIR "/sortie_loop_parity.trace"
                    : combat ? F15_GOLDEN_DIR "/sortie_combat_parity.trace"
                             : stick ? F15_GOLDEN_DIR "/sortie_stick_parity.trace"
                                     : land ? F15_GOLDEN_DIR "/sortie_land_parity.trace"
                                            : wrap ? F15_GOLDEN_DIR "/sortie_wrap_parity.trace"
                                                   : stall ? F15_GOLDEN_DIR "/sortie_stall_parity.trace"
                                                           : F15_GOLDEN_DIR "/sortie_parity.trace");
        result = runSortie(path, record, dump, profile);
    }
    teardown();
    if (!record && !fields && !dump) {
        if (land) {
            std::printf("land parity: %d ticks match the sortie_land golden\n",
                        ticksForProfile(profile));
        } else if (wrap) {
            std::printf("wrap parity: %d ticks match the sortie_wrap golden\n",
                        ticksForProfile(profile));
        } else if (stall) {
            std::printf("stall parity: %d ticks match the sortie_stall golden\n",
                        ticksForProfile(profile));
        } else {
            std::puts(loop ? "loop parity: 660 ticks match the sortie_loop golden"
                           : combat ? "combat parity: 900 ticks match the sortie_combat golden"
                                    : stick ? "stick parity: 660 ticks match the e28b9a4 stick-oracle golden"
                                            : "sortie parity: 660 ticks match the e28b9a4 golden");
        }
    }
    return result;
}
