file(MAKE_DIRECTORY "${BINARY_DIR}/math-compile-checks")
set(source "${SOURCE_DIR}/tests/typed_math_constraints.cpp")
set(object "${BINARY_DIR}/math-compile-checks/constraints.o")
if(USE_MSVC)
    set(flags /nologo /std:c++17 /EHsc /c "/I${SOURCE_DIR}/src" "${source}" "/Fo${object}")
    set(define /D)
else()
    set(flags -std=c++17 "-I${SOURCE_DIR}/src" -c "${source}" -o "${object}")
    set(define -D)
endif()
# First prove that this compiler/environment can compile the valid API example.
execute_process(COMMAND "${CXX}" ${flags} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Valid typed math example failed: ${out}\n${err}")
endif()
foreach(case PRIMITIVE_ANGLE PRIMITIVE_EULER RAW_EXTRACTION BACKEND_MIXING
             MATRIX_MIXING QUANTITY_MIXING PRIVATE_STORAGE UNGUARDED_BOUNDARY
             MATRIX_INDEX MATRIX_POINTER PRIMITIVE_ASSIGN PRIMITIVE_UPDATE
             FRAME_FRACTION ANGLE_POINTER CONTROL_AXIS CONTROL_BACKEND
             CONTROL_PRIMITIVE CONTROL_EXTRACTION CONTROL_ADD CONTROL_ANGLE
             CONTROL_STEP CONTROL_POINTER UNGUARDED_CONTROL_BOUNDARY
             ALTITUDE_PRIMITIVE ALTITUDE_EXTRACTION ALTITUDE_RENDER_MIX
             ALTITUDE_RATE_MIX ALTITUDE_BACKEND_MIX ALTITUDE_PRIMITIVE_STEP
             ALTITUDE_POINTER UNGUARDED_ALTITUDE_BOUNDARY
             COORDINATE_PRIMITIVE COORDINATE_EXTRACTION COORDINATE_AXIS COORDINATE_BACKEND
             COORDINATE_ADD DISPLACEMENT_AXIS DISPLACEMENT_PRIMITIVE HORIZONTAL_SPEED
             COORDINATE_POINTER UNGUARDED_HORIZONTAL_BOUNDARY
             AIRSPEED_PRIMITIVE AIRSPEED_EXTRACTION AIRSPEED_BACKEND AIRSPEED_RATE
             AIRSPEED_STEP AIRSPEED_POINTER AIRSPEED_SAMPLE UNGUARDED_AIRSPEED_BOUNDARY
             LIFT_PRIMITIVE TRIM_PRIMITIVE TRIM_BACKEND TRIM_COEFFICIENT TRIM_FRACTION
             STALL_PRIMITIVE STALL_EXTRACTION STALL_ROLE STALL_BACKEND STALL_SEVERITY STALL_STEP STALL_POINTER
             THRUST_PRIMITIVE THRUST_EXTRACTION THRUST_BACKEND THRUST_STEP THRUST_ROLE THRUST_POINTER
             THRUST_STORAGE UNGUARDED_PROPULSION_BOUNDARY)
    execute_process(COMMAND "${CXX}" ${flags} "${define}TEST_${case}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(result EQUAL 0)
        message(FATAL_ERROR "Compiler accepted forbidden math use: ${case}")
    endif()
endforeach()
