/* generated by tools/f19_deblob.py - see f19egvars.h */
#include "f19egvars.h"
#include <string.h>
extern const uint8 f19_egDsegImage[];

struct F19EGData f19_egSpace;

/* image bytes cover [0,0x9EC0); the rest is DOS BSS (zero). */
void f19_egVarsReset(void) {
    memcpy(&f19_egSpace, f19_egDsegImage, 40640);
    memset((char *)&f19_egSpace + 40640, 0, sizeof f19_egSpace - 40640);
}

typedef char f19_egLayoutChk[(sizeof f19_egSpace) == 0x10000 ? 1 : -1];
