/* Auto-generated: namespace every EGAME-port global with f19eg_ so the
 * ported F-19 gameplay cannot bind to (or be clobbered by) the app's
 * F-15 symbols of the same name. Included via f19eg.h in every port TU. */

#ifndef F19EGPFX_H
#define F19EGPFX_H
#define addTileEntry f19eg_addTileEntry
#define applyGravityFall f19eg_applyGravityFall
#define applyRotationDelta f19eg_applyRotationDelta
#define aspectScaleY f19eg_aspectScaleY
#define bearingToSimObject f19eg_bearingToSimObject
#define bearingToStore f19eg_bearingToStore
#define blitGaugeSprite f19eg_blitGaugeSprite
#define blitSprite f19eg_blitSprite
#define bombTarget f19eg_bombTarget
#define buildRangeString f19eg_buildRangeString
#define buildStoreName f19eg_buildStoreName
#define buildVertexSignMask f19eg_buildVertexSignMask
#define cacheScopePanel f19eg_cacheScopePanel
#define captureScopePanel f19eg_captureScopePanel
#define clampRange f19eg_clampRange
#define clampValue f19eg_clampValue
#define clearStatusPanel f19eg_clearStatusPanel
#define commitCommSnapshot f19eg_commitCommSnapshot
#define complementAngle f19eg_complementAngle
#define computeAimProjection f19eg_computeAimProjection
#define computeAttitudeAngles f19eg_computeAttitudeAngles
#define computeBearing f19eg_computeBearing
#define computeTargetBearing f19eg_computeTargetBearing
#define computeThreatRangeBearing f19eg_computeThreatRangeBearing
#define computeTileBounds f19eg_computeTileBounds
#define copyStoreToWaypoint f19eg_copyStoreToWaypoint
#define cosMul f19eg_cosMul
#define countermeasures f19eg_countermeasures
#define destroyGroundTarget f19eg_destroyGroundTarget
#define destroySimObject f19eg_destroySimObject
#define drawAirspeedTape f19eg_drawAirspeedTape
#define drawAirTargetInfoPanel f19eg_drawAirTargetInfoPanel
#define drawCenteredLabelBox f19eg_drawCenteredLabelBox
#define drawClippedLineRegion f19eg_drawClippedLineRegion
#define drawCockpit f19eg_drawCockpit
#define drawFullscreenLine f19eg_drawFullscreenLine
#define drawGaugeBar f19eg_drawGaugeBar
#define drawHudViewLine f19eg_drawHudViewLine
#define drawHudWorldOverlay f19eg_drawHudWorldOverlay
#define drawLoadoutPanel f19eg_drawLoadoutPanel
#define drawLockReticle f19eg_drawLockReticle
#define drawMapArc f19eg_drawMapArc
#define drawMapLine f19eg_drawMapLine
#define drawMapMarkerBox f19eg_drawMapMarkerBox
#define drawMapPoint f19eg_drawMapPoint
#define drawMapTileObject f19eg_drawMapTileObject
#define drawMapTiles f19eg_drawMapTiles
#define drawMissionObjectives f19eg_drawMissionObjectives
#define drawModelPoint f19eg_drawModelPoint
#define drawNearestTileObject f19eg_drawNearestTileObject
#define drawNumber f19eg_drawNumber
#define drawPanelGridText f19eg_drawPanelGridText
#define drawPanelModeText f19eg_drawPanelModeText
#define drawPanelText f19eg_drawPanelText
#define drawScreenLineOnePage f19eg_drawScreenLineOnePage
#define drawStatusBar f19eg_drawStatusBar
#define drawStatusItem f19eg_drawStatusItem
#define drawStringActivePage f19eg_drawStringActivePage
#define drawStringBothPages f19eg_drawStringBothPages
#define drawStringCentered f19eg_drawStringCentered
#define drawTacticalMap f19eg_drawTacticalMap
#define drawTargetBox f19eg_drawTargetBox
#define drawTargetInfoPanel f19eg_drawTargetInfoPanel
#define drawTargetLabel f19eg_drawTargetLabel
#define drawTargetView f19eg_drawTargetView
#define drawThreatIndicator f19eg_drawThreatIndicator
#define drawViewportLine f19eg_drawViewportLine
#define drawWaypointPanel f19eg_drawWaypointPanel
#define drawWeaponRadarInfo f19eg_drawWeaponRadarInfo
#define drawWeaponsPanel f19eg_drawWeaponsPanel
#define drawWorldObject f19eg_drawWorldObject
#define exitTimeAccel f19eg_exitTimeAccel
#define F19EGPFX_H
#define fillPanelBox f19eg_fillPanelBox
#define fillRectBoth f19eg_fillRectBoth
#define findNearestTileObject f19eg_findNearestTileObject
#define findStoreAtGrid f19eg_findStoreAtGrid
#define findWaypointFeatures f19eg_findWaypointFeatures
#define fireAirThreat f19eg_fireAirThreat
#define fireGroundThreat f19eg_fireGroundThreat
#define fireMissile f19eg_fireMissile
#define formatMissionClock f19eg_formatMissionClock
#define formatTwoDigit f19eg_formatTwoDigit
#define getStoreMapCode f19eg_getStoreMapCode
#define getTimeOfDay f19eg_getTimeOfDay
#define getWeaponStat f19eg_getWeaponStat
#define gfxInit f19eg_gfxInit
#define hudMessage f19eg_hudMessage
#define hudPitchScale f19eg_hudPitchScale
#define initFlightParams f19eg_initFlightParams
#define initFrameRandom f19eg_initFrameRandom
#define initStoreData f19eg_initStoreData
#define initTacMapView f19eg_initTacMapView
#define initWeaponLoadout f19eg_initWeaponLoadout
#define insertOutlineEdges f19eg_insertOutlineEdges
#define isqrt f19eg_isqrt
#define isTargetOverWater f19eg_isTargetOverWater
#define keyDispatch f19eg_keyDispatch
#define load15Flt3d3 f19eg_load15Flt3d3
#define load3D3 f19eg_load3D3
#define load3DAll f19eg_load3DAll
#define load3DG f19eg_load3DG
#define load3DT f19eg_load3DT
#define initMissionStrings f19eg_load3DAll   /* sub_10446 = trampoline -> sub_10ABE */
#define placeString f19eg_buildStoreName     /* sub_14D03 = buildStoreName (egframe) */
#define setupDac f19eg_setupDac              /* sub_11BB4 — F-19 full-256 DAC table */
#define loadColorPalette f19eg_loadColorPalette
#define loadFileNear f19eg_loadFileNear
#define loadFileSection f19eg_loadFileSection
#define lookupTileEntry f19eg_lookupTileEntry
#define main f19eg_main
#define makeSound f19eg_makeSound
#define mapXToScreen f19eg_mapXToScreen
#define mapYToScreen f19eg_mapYToScreen
#define markTargetReached f19eg_markTargetReached
#define matVecDotAxis f19eg_matVecDotAxis
#define moveDataFar f19eg_moveDataFar
#define moveNearFar f19eg_moveNearFar
#define moveStuff f19eg_moveStuff
#define plotMapObject f19eg_plotMapObject
#define printError f19eg_printError
#define process3dg f19eg_process3dg
#define projectMapPoint f19eg_projectMapPoint
#define projectModelVertices f19eg_projectModelVertices
#define projectObjects f19eg_projectObjects
#define projectWorldPoint f19eg_projectWorldPoint
#define randomRange f19eg_randomRange
#define rangeApprox f19eg_rangeApprox
#define rasterize3DWorld f19eg_rasterize3DWorld
#define readAxisInput f19eg_readAxisInput
#define readMapPixelColor f19eg_readMapPixelColor
#define readScreenPixel f19eg_readScreenPixel
#define rebuildOrientation f19eg_rebuildOrientation
#define recalcTimeScale f19eg_recalcTimeScale
#define recordFrame f19eg_recordFrame
#define redrawTacMap f19eg_redrawTacMap
#define render3DView f19eg_render3DView
#define renderFrame f19eg_renderFrame
#define renderHudFrame f19eg_renderHudFrame
#define renderMapTerrain f19eg_renderMapTerrain
#define resetSimObjectLocks f19eg_resetSimObjectLocks
#define restoreScopePanel f19eg_restoreScopePanel
#define runGameSession f19eg_runGameSession
#define samCanAcquireTarget f19eg_samCanAcquireTarget
#define scaleCoordToLod f19eg_scaleCoordToLod
#define seedRng f19eg_seedRng
#define sendSoundCmd f19eg_sendSoundCmd
#define setCommWorldbufPtr f19eg_setCommWorldbufPtr
#define setDrawColor f19eg_setDrawColor
#define setup3DTransform f19eg_setup3DTransform
#define setupInstrumentLayoutFar f19eg_setupInstrumentLayoutFar
#define setupLodDistances f19eg_setupLodDistances
#define setupViewport f19eg_setupViewport
#define setViewPosition f19eg_setViewPosition
#define setViewRotation f19eg_setViewRotation
#define shapeDataOffset f19eg_shapeDataOffset
#define signedRatio16 f19eg_signedRatio16
#define signExtendByte f19eg_signExtendByte
#define signOf f19eg_signOf
#define sinMul f19eg_sinMul
#define spawnEnemyAircraft f19eg_spawnEnemyAircraft
#define spawnSamThreat f19eg_spawnSamThreat
#define stepFlightModel f19eg_stepFlightModel
#define strcpyFromDot f19eg_strcpyFromDot
#define tickWeaponSlots f19eg_tickWeaponSlots
#define updateBulletsAndFire f19eg_updateBulletsAndFire
#define updateEngineSound f19eg_updateEngineSound
#define updateFrame f19eg_updateFrame
#define updateHudGauge f19eg_updateHudGauge
#define updateObjects f19eg_updateObjects
#define updatePanelMode f19eg_updatePanelMode
#define updateStatusPanel f19eg_updateStatusPanel
#define updateTargetingHud f19eg_updateTargetingHud
#define updateThreatAlert f19eg_updateThreatAlert
#define updateThreatSites f19eg_updateThreatSites
#define updateThreatTargeting f19eg_updateThreatTargeting
#define updateTracerParticles f19eg_updateTracerParticles
#define valueToAngle f19eg_valueToAngle
#define waitForKeyPress f19eg_waitForKeyPress
#define waitFrameSync f19eg_waitFrameSync
#define worldToTileIndex f19eg_worldToTileIndex
#define writeFileSection f19eg_writeFileSection
#define zoomIn f19eg_zoomIn
#define zoomOut f19eg_zoomOut

#endif /* F19EGPFX_H */
