/* generated by tools/f19_enseg.py — END.EXE data segment as named
 * globals (the debrief/debrief-map world). All dseg cells are members of
 * one packed struct at their exact DOS offsets, so indexed and overlapping
 * accesses see contiguous DOS-ordered storage.  World 2 in f19seg.c. */
#ifndef F19ENVARS_H
#define F19ENVARS_H
#include "inttype.h"
#include "f19seg.h"

#pragma pack(push, 1)
struct F19ENData {
    uint8 f19_engap_0[8];   /* gap */      /* 0x00000 */
    uint8 m_recField8;                      /* 0x00008 */
    uint8 m_recField9[57];                /* 0x00009 */
    int16 m_weaponDataBlock[12];                /* 0x00042 */
    uint8 m_recActive[8];                /* 0x0005A */
    uint8 m_samFlagTab[310];                /* 0x00062 */
    uint8 m_planeArray[24];                /* 0x00198 */
    uint8 m_planeObjects[584];                /* 0x001B0 */
    uint8 m_samWeaponTable[804];                /* 0x003F8 */
    int16 m_nightMission[5];                /* 0x0071C */
    char m_wpnNames[1570];                /* 0x00726 */
    uint8 m_word_1AAD8[2103];                /* 0x00D48 */
    int16 m_lineX1;                      /* 0x0157F */
    int16 m_lineX2;                      /* 0x01581 */
    int16 m_lineY1;                      /* 0x01583 */
    int16 m_lineY2[450];                /* 0x01585 */
    int16 m_clipMaxX;                      /* 0x01909 */
    uint8 m_clipMaxY[51];                /* 0x0190B */
    int8 m_byte_1D6CE;                      /* 0x0193E */
    uint8 m_joyAxisY[3];                /* 0x0193F */
    uint8 m_quitFlag[8];                /* 0x01942 */
    uint8 m_picStreamBuf[618];                /* 0x0194A */
    int16 m_word_1B544[167];                /* 0x01BB4 */
    int16 m_word_1BA92[6];                /* 0x01D02 */
    int16 m_word_1BA9E[24];                /* 0x01D0E */
    uint8 m_word_1BACE[2];                /* 0x01D3E */
    uint8 m_word_1BAD0[2];                /* 0x01D40 */
    uint8 m_word_1BAD2[2];                /* 0x01D42 */
    uint8 m_word_1BAD4[6];                /* 0x01D44 */
    int16 m_word_1BADA;                      /* 0x01D4A */
    int16 m_word_1BADC;                      /* 0x01D4C */
    int16 m_word_1BADE;                      /* 0x01D4E */
    int16 m_word_1BAE0;                      /* 0x01D50 */
    int16 m_word_1BAE2[1535];                /* 0x01D52 */
    uint8 m_byte_1C6E0;                      /* 0x02950 */
    uint8 m_byte_1C6E1;                      /* 0x02951 */
    uint8 m_byte_1C6E2;                      /* 0x02952 */
    uint8 m_byte_1C6E3;                      /* 0x02953 */
    uint8 m_byte_1C6E4;                      /* 0x02954 */
    uint8 m_byte_1C6E5;                      /* 0x02955 */
    uint8 m_byte_1C6E6[2];                /* 0x02956 */
    uint8 m_word_1C6E8[2];                /* 0x02958 */
    uint8 m_word_1C6EA[2];                /* 0x0295A */
    int16 m_tickArm;                      /* 0x0295C */
    uint8 m_recTable[4065];                /* 0x0295E */
    int8 m_dseg_393F[885];                 /* 0x0393F */
    int16 m_recCount;                      /* 0x03CB4 */
    int16 m_word_1DA46;                      /* 0x03CB6 */
    int16 m_word_1DA48[635];                /* 0x03CB8 */
    int16 m_word_1DF3E;                      /* 0x041AE */
    int16 m_word_1DF40;                      /* 0x041B0 */
    int16 m_word_1DF42;                      /* 0x041B2 */
    uint8 m_byte_1DF44[2];                /* 0x041B4 */
    int16 m_word_1DF46;                      /* 0x041B6 */
    int16 m_word_1DF48;                      /* 0x041B8 */
    int16 m_word_1DF4A;                      /* 0x041BA */
    uint8 m_byte_1DF4C[3];                /* 0x041BC */
    uint8 m_timerHandlerInstalled[27];                /* 0x041BF */
    uint8 m_byte_1DF6A;                      /* 0x041DA */
    uint8 m_tickByte;                      /* 0x041DB */
    uint8 m_timerCounter2;                      /* 0x041DC */
    uint8 m_timerCounter3;                      /* 0x041DD */
    uint16 m_colorStyleTable[16];                /* 0x041DE */
    int16 m_mapWinX1;                      /* 0x041FE */
    int16 m_mapWinY1;                      /* 0x04200 */
    int16 m_mapWinX2;                      /* 0x04202 */
    int16 m_mapWinY2;                      /* 0x04204 */
    int16 m_awardPrim[3];                /* 0x04206 */
    int16 m_awardSec[2];                /* 0x0420C */
    int16 m_awardVisId[3];                /* 0x04210 */
    int16 m_awardArmedGnd[3];                /* 0x04216 */
    int16 m_awardUnitChk[3];                /* 0x0421C */
    int16 m_awardCivilian[3];                /* 0x04222 */
    int16 m_awardUnarmedGnd[3];                /* 0x04228 */
    int16 m_awardFriendlyGnd[3];                /* 0x0422E */
    int16 m_awardRadarId[3];                /* 0x04234 */
    int16 m_award423a[3];                /* 0x0423A */
    int16 m_award4240[3];                /* 0x04240 */
    int16 m_award4246[3];                /* 0x04246 */
    int16 m_award424c[3];                /* 0x0424C */
    int16 m_award4252[3];                /* 0x04252 */
    int16 m_awardUnit[48];                /* 0x04258 */
    int16 m_multTheater[5];                /* 0x042B8 */
    int16 m_multMission[4];                /* 0x042C2 */
    int16 m_multDiff[4];                /* 0x042CA */
    int16 m_multUnk[3];                /* 0x042D2 */
    int16 m_multResult[250];                /* 0x042D8 */
    int16 m_word_1E25C[18];                /* 0x044CC */
    int16 m_word_1E280[18];                /* 0x044F0 */
    int16 m_word_1E2A4[315];                /* 0x04514 */
    int16 m_word_1E51A[336];                /* 0x0478A */
    int16 m_word_1E7BA[141];                /* 0x04A2A */
    int16 m_word_1E8D4[183];                /* 0x04B44 */
    int16 m_word_1EA42[360];                /* 0x04CB2 */
    uint8 m_word_1ED12[1812];                /* 0x04F82 */
    uint8 m_word_1F426[74];                /* 0x05696 */
    int16 m_rankNames[18];                /* 0x056E0 */
    uint8 m_word_19704[170];                /* 0x05704 */
    uint8 m_word_1981E[88];                /* 0x057AE */
    uint8 m_word_19806[182];                /* 0x05806 */
    uint8 m_evtItems[24];                /* 0x058BC */
    uint8 m_word_1F664[28];                /* 0x058D4 */
    int16 m_word_1F6A4[2];                /* 0x058F0 */
    uint8 m_spriteMapArea[64];                /* 0x058F4 */
    uint8 m_spriteAir[32];                /* 0x05934 */
    uint8 m_spriteAirBlink[32];                /* 0x05954 */
    uint8 m_spriteGround[32];                /* 0x05974 */
    uint8 m_spriteGroundBlink[32];                /* 0x05994 */
    uint8 m_spriteSam[32];                /* 0x059B4 */
    uint8 m_spriteSamBlink[96];                /* 0x059D4 */
    uint8 m_spriteWaypoint[32];                /* 0x05A34 */
    uint8 m_spriteWaypointBlink[2];                /* 0x05A54 */
    uint8 m_menuItems[112];                /* 0x05A56 */
    uint8 m_word_1F856[2];                /* 0x05AC6 */
    int16 m_word_1F858[4];                /* 0x05AC8 */
    int16 m_word_1F860[907];                /* 0x05AD0 */
    uint8 m_awardTextItem[2];                /* 0x061E6 */
    int16 m_awardStatGrid[330];                /* 0x061E8 */
    int16 m_ribbonItems[255];                /* 0x0647C */
    uint8 m_rankSpriteA[14];                /* 0x0667A */
    uint8 m_rankSpriteB[14];                /* 0x06688 */
    uint8 m_rankSpriteC[12];                /* 0x06696 */
    uint8 m_medalSpriteTab[12];                /* 0x066A2 */
    uint8 m_purpleHeartSpr[24];                /* 0x066AE */
    uint16 m_promoScoreMin[6];                /* 0x066C6 */
    uint16 m_promoAvgMin[6];                /* 0x066D2 */
    uint16 m_promoMissionsMin[5];                /* 0x066DE */
    uint8 m_medalNames[12];                /* 0x066E8 */
    uint8 m_queuedAwardName[10];                /* 0x066F4 */
    uint8 m_ribbonNames[8];                /* 0x066FE */
    uint8 m_newRankNames[8];                /* 0x06706 */
    int16 m_ribbonIcons[3];                /* 0x0670E */
    uint8 m_nextRankNames[156];                /* 0x06714 */
    int16 m_ribbonPos[313];                /* 0x067B0 */
    uint8 m_word_207B2[235];                /* 0x06A22 */
    uint8 m_byte_2089D[16];                /* 0x06B0D */
    uint8 m_byte_208AD[16];                /* 0x06B1D */
    uint8 m_byte_208BD[16];                /* 0x06B2D */
    uint8 m_byte_208CD[233];                /* 0x06B3D */
    uint8 m_worldBufPtr[6762];                /* 0x06C26 */
    uint8 m_colorTablePtr[2];                /* 0x08690 */
    uint8 m_inputChanged[2];                /* 0x08692 */
    int16 m_colorAnimIdx;                      /* 0x08694 */
    int16 m_colorAnimEnabled;                      /* 0x08696 */
    uint8 m_joyRepeatFlag;                      /* 0x08698 */
    uint8 m_spriteToggle;                      /* 0x08699 */
    uint8 m_animDone[6];                /* 0x0869A */
    int16 m_awardQueued[3];                /* 0x086A0 */
    int16 m_worldMiscHeader[2];                /* 0x086A6 */
    int16 m_worldBufHandle;                      /* 0x086AA */
    int16 m_awardTrained[4];                /* 0x086AC */
    int16 m_missionRibbon;                      /* 0x086B4 */
    int16 m_worldRouteTable[2];                /* 0x086B6 */
    int16 m_promotionDone;                      /* 0x086BA */
    int16 m_word_2244C;                      /* 0x086BC */
    int16 m_promotionPending;                      /* 0x086BE */
    int8 m_byte_22450;                      /* 0x086C0 */
    uint8 m_ms_airKilled;                      /* 0x086C1 */
    uint8 m_ms_friendlyAir[4];                /* 0x086C2 */
    uint8 m_worldObjects[8];                /* 0x086C6 */
    uint8 m_slotInfoTable[1192];                /* 0x086CE */
    uint8 m_drawTextMode[4];                /* 0x08B76 */
    uint8 m_gridFlags[256];                /* 0x08B7A */
    int16 m_targetBlockWd[4];                /* 0x08C7A */
    uint8 m_word_22A12[28];                /* 0x08C82 */
    char m_scoreString[512];                /* 0x08C9E */
    int16 m_award6Flag[2];                /* 0x08E9E */
    int16 m_word_18EA2;                      /* 0x08EA2 */
    int16 m_word_22C34;                      /* 0x08EA4 */
    int16 m_curRecordIdx;                      /* 0x08EA6 */
    int16 m_worldSamTable[360];                /* 0x08EA8 */
    int8 m_byte_22F08[2];                /* 0x09178 */
    int16 m_word_22F0A[2];                /* 0x0917A */
    uint8 m_ms_unauthGround[2];                /* 0x0917E */
    int16 m_totalFlightRecords;                      /* 0x09180 */
    int16 m_flightTimeTable;                      /* 0x09182 */
    uint8 m_flightRecords[1534];                /* 0x09184 */
    int16 m_selectedMenuItem[2];                /* 0x09782 */
    int16 m_awardCode[2];                /* 0x09786 */
    uint8 m_ms_groundKilled;                      /* 0x0978A */
    uint8 m_ms_friendlyGnd;                      /* 0x0978B */
    int16 m_missionResult;                      /* 0x0978C */
    uint8 m_word_2351E[401];                /* 0x0978E */
    uint8 m_enterPressed;                      /* 0x0991F */
    int16 m_worldObjectCount;                      /* 0x09920 */
    int16 m_worldUnitFlags[50];                /* 0x09922 */
    uint8 m_ms_unauthAir[4];                /* 0x09986 */
    int8 m_unitTypeTable[100];                /* 0x0998A */
    int16 m_word_2377E;                      /* 0x099EE */
    int16 m_worldGridSize;                      /* 0x099F0 */
    int16 m_worldDataReady;                      /* 0x099F2 */
    uint8 m_promoScreenOpen;                      /* 0x099F4 */
    uint8 m_ms_civilian;                      /* 0x099F5 */
    int16 m_word_23786;                      /* 0x099F6 */
    int16 m_word_23788;                      /* 0x099F8 */
    int16 m_worldWaypointCount[3];                /* 0x099FA */
    int16 m_prevDrawY[3];                /* 0x09A00 */
    uint8 m_ejectedFlag[2];                /* 0x09A06 */
    int16 m_lastDrawX;                      /* 0x09A08 */
    int16 m_prevDrawX;                      /* 0x09A0A */
    int16 m_word_2379C;                      /* 0x09A0C */
    uint8 m_word_2379E[2];                /* 0x09A0E */
    uint16 m_cursorX[3];                /* 0x09A10 */
    uint16 m_cursorY[2];                /* 0x09A16 */
    uint8 m_popupVisible;                      /* 0x09A1A */
    uint8 m_target1Scored;                      /* 0x09A1B */
    int16 m_worldSamCount[103];                /* 0x09A1C */
    int16 m_word_2387A;                      /* 0x09AEA */
    char m_worldStringBuf[750];                /* 0x09AEC */
    int32 m_missionScore;                      /* 0x09DDA */
    uint8 m_target2Scored[242];                /* 0x09DDE */
    int16 m_popupY;                      /* 0x09ED0 */
    int16 m_word_23C62;                      /* 0x09ED2 */
    int16 m_worldRouteCount[4];                /* 0x09ED4 */
    int16 m_word_23C6C;                      /* 0x09EDC */
    int16 m_popupX[2];                /* 0x09EDE */
    int16 m_word_23C72;                      /* 0x09EE2 */
    int16 m_word_23C74;                      /* 0x09EE4 */
    int16 m_word_23C76;                      /* 0x09EE6 */
    int16 m_word_23C78;                      /* 0x09EE8 */
    int16 m_word_23C7A;                      /* 0x09EEA */
    int16 m_word_23C7C[2];                /* 0x09EEC */
};
#pragma pack(pop)

extern struct F19ENData f19_enSpace;
extern const struct F19ENData f19_enInit;
void f19_enVarsReset(void);

#define recField8 ((uint8*)f19_enSpace.m_recField8)
#define recField9 ((uint8*)f19_enSpace.m_recField9)
#define weaponDataBlock ((int16*)f19_enSpace.m_weaponDataBlock)
#define recActive ((uint8*)f19_enSpace.m_recActive)
#define samFlagTab ((uint8*)f19_enSpace.m_samFlagTab)
#define planeArray ((struct PlaneNameEnd*)f19_enSpace.m_planeArray)
#define planeObjects ((struct PlaneObjEnd*)f19_enSpace.m_planeObjects)
#define samWeaponTable ((struct SamNameEnd*)f19_enSpace.m_samWeaponTable)
#define nightMission (*(int16 *)&f19_enSpace.m_nightMission)
#define wpnNames ((char(*)[0x1a])f19_enSpace.m_wpnNames)
#define word_1AAD8 ((struct OrdType*)f19_enSpace.m_word_1AAD8)
#define lineX1 (*(int16 *)&f19_enSpace.m_lineX1)
#define lineX2 (*(int16 *)&f19_enSpace.m_lineX2)
#define lineY1 (*(int16 *)&f19_enSpace.m_lineY1)
#define lineY2 (*(int16 *)&f19_enSpace.m_lineY2)
#define clipMaxX (*(int16 *)&f19_enSpace.m_clipMaxX)
#define clipMaxY (*(uint8 *)&f19_enSpace.m_clipMaxY)
#define byte_1D6CE (*(int8 *)&f19_enSpace.m_byte_1D6CE)
#define joyAxisX (*(uint8 *)((uint8 *)&f19_enSpace.m_byte_1D6CE + 0))
#define joyAxisY (*(uint8 *)&f19_enSpace.m_joyAxisY)
#define quitFlag (*(uint8 *)&f19_enSpace.m_quitFlag)
#define byte_1D6D2 (*(int8 *)((uint8 *)&f19_enSpace.m_quitFlag + 0))
#define picStreamBuf ((uint8*)f19_enSpace.m_picStreamBuf)
#define word_1B544 (*(int16 *)&f19_enSpace.m_word_1B544)
#define word_1BA92 (*(int16 *)&f19_enSpace.m_word_1BA92)
#define word_1BA9E (*(int16 *)&f19_enSpace.m_word_1BA9E)
#define word_1BADA (*(int16 *)&f19_enSpace.m_word_1BADA)
#define word_1BADC (*(int16 *)&f19_enSpace.m_word_1BADC)
#define word_1BADE (*(int16 *)&f19_enSpace.m_word_1BADE)
#define word_1BAE0 ((int16 *)&f19_enSpace.m_word_1BAE0)
#define word_1BAE2 ((int16*)f19_enSpace.m_word_1BAE2)
#define byte_1C6E0 (*(uint8 *)&f19_enSpace.m_byte_1C6E0)
#define byte_1C6E1 (*(uint8 *)&f19_enSpace.m_byte_1C6E1)
#define byte_1C6E2 (*(uint8 *)&f19_enSpace.m_byte_1C6E2)
#define byte_1C6E3 (*(uint8 *)&f19_enSpace.m_byte_1C6E3)
#define byte_1C6E4 (*(uint8 *)&f19_enSpace.m_byte_1C6E4)
#define byte_1C6E5 (*(uint8 *)&f19_enSpace.m_byte_1C6E5)
#define byte_1C6E6 (*(uint8 *)&f19_enSpace.m_byte_1C6E6)
#define tickArm (*(int16 *)&f19_enSpace.m_tickArm)
#define word_1295C (*(int16 *)((uint8 *)&f19_enSpace.m_tickArm + 0))
#define recTable ((struct MapRect*)f19_enSpace.m_recTable)
#define byte_1D6CF (*(int8 *)&f19_enSpace.m_joyAxisY)   /* src_end name for dseg:0x193F (joyAxisY), not the 0x393F label */
#define recCount (*(int16 *)&f19_enSpace.m_recCount)
#define word_1DA44 (*(int16 *)((uint8 *)&f19_enSpace.m_recCount + 0))
#define word_1DA46 (*(int16 *)&f19_enSpace.m_word_1DA46)
#define word_1DA48 (*(int16 *)&f19_enSpace.m_word_1DA48)
#define word_1DF3E (*(int16 *)&f19_enSpace.m_word_1DF3E)
#define word_1DF40 (*(int16 *)&f19_enSpace.m_word_1DF40)
#define word_1DF42 (*(int16 *)&f19_enSpace.m_word_1DF42)
#define byte_1DF44 (*(uint8 *)&f19_enSpace.m_byte_1DF44)
#define word_1DF46 (*(int16 *)&f19_enSpace.m_word_1DF46)
#define word_1DF48 (*(int16 *)&f19_enSpace.m_word_1DF48)
#define word_1DF4A (*(int16 *)&f19_enSpace.m_word_1DF4A)
#define byte_1DF4C (*(uint8 *)&f19_enSpace.m_byte_1DF4C)
#define timerHandlerInstalled (*(uint8 *)&f19_enSpace.m_timerHandlerInstalled)
#define byte_1DF6A (*(uint8 *)&f19_enSpace.m_byte_1DF6A)
#define tickByte (*(uint8 *)&f19_enSpace.m_tickByte)
#define timerCounter2 (*(uint8 *)&f19_enSpace.m_timerCounter2)
#define timerCounter3 (*(uint8 *)&f19_enSpace.m_timerCounter3)
#define colorStyleTable ((uint16*)f19_enSpace.m_colorStyleTable)
#define mapWinX1 (*(int16 *)&f19_enSpace.m_mapWinX1)
#define mapWinY1 (*(int16 *)&f19_enSpace.m_mapWinY1)
#define mapWinX2 (*(int16 *)&f19_enSpace.m_mapWinX2)
#define mapWinY2 (*(int16 *)&f19_enSpace.m_mapWinY2)
#define awardPrim ((int16*)f19_enSpace.m_awardPrim)
#define awardSec ((int16*)f19_enSpace.m_awardSec)
#define awardVisId ((int16*)f19_enSpace.m_awardVisId)
#define awardArmedGnd ((int16*)f19_enSpace.m_awardArmedGnd)
#define awardUnitChk ((int16*)f19_enSpace.m_awardUnitChk)
#define awardCivilian ((int16*)f19_enSpace.m_awardCivilian)
#define awardUnarmedGnd ((int16*)f19_enSpace.m_awardUnarmedGnd)
#define awardFriendlyGnd ((int16*)f19_enSpace.m_awardFriendlyGnd)
#define awardRadarId ((int16*)f19_enSpace.m_awardRadarId)
#define award423a ((int16*)f19_enSpace.m_award423a)
#define award4240 ((int16*)f19_enSpace.m_award4240)
#define award4246 ((int16*)f19_enSpace.m_award4246)
#define award424c ((int16*)f19_enSpace.m_award424c)
#define award4252 ((int16*)f19_enSpace.m_award4252)
#define awardUnit ((int16(*)[16])f19_enSpace.m_awardUnit)
#define multTheater ((int16*)f19_enSpace.m_multTheater)
#define multMission ((int16*)f19_enSpace.m_multMission)
#define multDiff ((int16*)f19_enSpace.m_multDiff)
#define multUnk ((int16*)f19_enSpace.m_multUnk)
#define multResult ((int16*)f19_enSpace.m_multResult)
#define word_1E25C ((int16*)f19_enSpace.m_word_1E25C)
#define word_1E280 ((int16*)f19_enSpace.m_word_1E280)
#define word_1E2A4 (*(int16 *)&f19_enSpace.m_word_1E2A4)
#define word_1E51A (*(int16 *)&f19_enSpace.m_word_1E51A)
#define word_1E7BA (*(int16 *)&f19_enSpace.m_word_1E7BA)
#define word_1E8D4 (*(int16 *)&f19_enSpace.m_word_1E8D4)
#define word_1EA42 (*(int16 *)&f19_enSpace.m_word_1EA42)
#define rankNames ((int16*)f19_enSpace.m_rankNames)
#define evtItems ((struct EvtItem*)f19_enSpace.m_evtItems)
#define word_1F6A4 (*(int16 *)&f19_enSpace.m_word_1F6A4)
#define menuItems ((MenuItem*)f19_enSpace.m_menuItems)
#define word_1F858 ((int16*)f19_enSpace.m_word_1F858)
#define word_1F860 ((int16*)f19_enSpace.m_word_1F860)
#define awardStatGrid ((int16(*)[45])f19_enSpace.m_awardStatGrid)
#define ribbonItems ((int16(*)[15])f19_enSpace.m_ribbonItems)
#define promoScoreMin ((uint16*)f19_enSpace.m_promoScoreMin)
#define promoAvgMin ((uint16*)f19_enSpace.m_promoAvgMin)
#define promoMissionsMin ((uint16*)f19_enSpace.m_promoMissionsMin)
#define ribbonIcons ((int16(*)[9])f19_enSpace.m_ribbonIcons)
#define ribbonPos ((int16(*)[9])f19_enSpace.m_ribbonPos)
#define byte_2089D ((uint8*)f19_enSpace.m_byte_2089D)
#define byte_208AD ((uint8*)f19_enSpace.m_byte_208AD)
#define byte_208BD ((uint8*)f19_enSpace.m_byte_208BD)
#define byte_208CD ((uint8*)f19_enSpace.m_byte_208CD)
#define inputChanged (*(uint8 *)&f19_enSpace.m_inputChanged)
#define colorAnimIdx (*(int16 *)&f19_enSpace.m_colorAnimIdx)
#define colorAnimEnabled (*(int16 *)&f19_enSpace.m_colorAnimEnabled)
#define joyRepeatFlag (*(uint8 *)&f19_enSpace.m_joyRepeatFlag)
#define spriteToggle (*(uint8 *)&f19_enSpace.m_spriteToggle)
#define animDone (*(uint8 *)&f19_enSpace.m_animDone)
#define awardQueued (*(int16 *)&f19_enSpace.m_awardQueued)
#define worldMiscHeader ((int16 *)f19_enSpace.m_worldMiscHeader)
#define worldBufHandle (*(int16 *)&f19_enSpace.m_worldBufHandle)
#define awardTrained (*(int16 *)&f19_enSpace.m_awardTrained)
#define missionRibbon (*(int16 *)&f19_enSpace.m_missionRibbon)
#define worldRouteTable ((int16*)f19_enSpace.m_worldRouteTable)
#define promotionDone (*(int16 *)&f19_enSpace.m_promotionDone)
#define word_2244C (*(int16 *)&f19_enSpace.m_word_2244C)
#define word_226BC (*(int16 *)((uint8 *)&f19_enSpace.m_word_2244C + 0))
#define promotionPending (*(int16 *)&f19_enSpace.m_promotionPending)
#define byte_22450 (*(int8 *)&f19_enSpace.m_byte_22450)
#define ms_airKilled (*(uint8 *)&f19_enSpace.m_ms_airKilled)
#define ms_friendlyAir (*(uint8 *)&f19_enSpace.m_ms_friendlyAir)
#define worldObjects ((struct WorldObjEnd*)f19_enSpace.m_worldObjects)
#define slotInfoTable ((uint8*)f19_enSpace.m_slotInfoTable)
#define drawTextMode (*(uint8 *)&f19_enSpace.m_drawTextMode)
#define initResultFlag (*(int16 *)((uint8 *)&f19_enSpace.m_drawTextMode + 0))
#define gridFlags ((uint8(*)[16])f19_enSpace.m_gridFlags)
#define targetBlockWd ((int16*)f19_enSpace.m_targetBlockWd)
#define word_22A12 ((struct UnitInfo*)f19_enSpace.m_word_22A12)
#define scoreString ((char*)f19_enSpace.m_scoreString)
#define award6Flag (*(int16 *)&f19_enSpace.m_award6Flag)
#define word_18EA2 (*(int16 *)&f19_enSpace.m_word_18EA2)
#define word_22C34 (*(int16 *)&f19_enSpace.m_word_22C34)
#define curRecordIdx (*(int16 *)&f19_enSpace.m_curRecordIdx)
#define word_18EA6 (*(int16 *)((uint8 *)&f19_enSpace.m_curRecordIdx + 0))
#define worldSamTable ((int16*)f19_enSpace.m_worldSamTable)
#define byte_22F08 (*(int8 *)&f19_enSpace.m_byte_22F08)
#define word_22F0A (*(int16 *)&f19_enSpace.m_word_22F0A)
#define ms_unauthGround (*(uint8 *)&f19_enSpace.m_ms_unauthGround)
#define totalFlightRecords (*(int16 *)&f19_enSpace.m_totalFlightRecords)
#define word_22F10 (*(int16 *)((uint8 *)&f19_enSpace.m_totalFlightRecords + 0))
#define flightTimeTable ((int16 *)&f19_enSpace.m_flightTimeTable)
#define flightDataBuf ((uint8 *)&f19_enSpace.m_flightTimeTable)
#define flightRecords ((struct FlightLogRec*)f19_enSpace.m_flightRecords)
#define selectedMenuItem (*(int16 *)&f19_enSpace.m_selectedMenuItem)
#define awardCode (*(int16 *)&f19_enSpace.m_awardCode)
#define ms_groundKilled (*(uint8 *)&f19_enSpace.m_ms_groundKilled)
#define ms_friendlyGnd (*(uint8 *)&f19_enSpace.m_ms_friendlyGnd)
#define missionResult (*(int16 *)&f19_enSpace.m_missionResult)
#define word_2351E ((int16*)f19_enSpace.m_word_2351E)
#define enterPressed (*(uint8 *)&f19_enSpace.m_enterPressed)
#define worldObjectCount (*(int16 *)&f19_enSpace.m_worldObjectCount)
#define worldUnitFlags ((int16*)f19_enSpace.m_worldUnitFlags)
#define ms_unauthAir (*(uint8 *)&f19_enSpace.m_ms_unauthAir)
#define unitTypeTable ((int8*)f19_enSpace.m_unitTypeTable)
#define word_2377E (*(int16 *)&f19_enSpace.m_word_2377E)
#define worldGridSize (*(int16 *)&f19_enSpace.m_worldGridSize)
#define worldDataReady (*(int16 *)&f19_enSpace.m_worldDataReady)
#define promoScreenOpen (*(uint8 *)&f19_enSpace.m_promoScreenOpen)
#define byte_199F4 (*(int8 *)((uint8 *)&f19_enSpace.m_promoScreenOpen + 0))
#define ms_civilian (*(uint8 *)&f19_enSpace.m_ms_civilian)
#define word_23786 (*(int16 *)&f19_enSpace.m_word_23786)
#define mapViewX1 (*(int16 *)((uint8 *)&f19_enSpace.m_word_23786 + 0))
#define word_23788 (*(int16 *)&f19_enSpace.m_word_23788)
#define mapViewY1 (*(int16 *)((uint8 *)&f19_enSpace.m_word_23788 + 0))
#define worldWaypointCount (*(int16 *)&f19_enSpace.m_worldWaypointCount)
#define prevDrawY (*(int16 *)&f19_enSpace.m_prevDrawY)
#define lastDrawY (*(int16 *)((uint8 *)&f19_enSpace.m_prevDrawY + 0))
#define ejectedFlag (*(uint8 *)&f19_enSpace.m_ejectedFlag)
#define byte_23796 (*(int8 *)((uint8 *)&f19_enSpace.m_ejectedFlag + 0))
#define lastDrawX (*(int16 *)&f19_enSpace.m_lastDrawX)
#define prevDrawX (*(int16 *)&f19_enSpace.m_prevDrawX)
#define word_2379C (*(int16 *)&f19_enSpace.m_word_2379C)
#define cursorX (*(uint16 *)&f19_enSpace.m_cursorX)
#define cursorY (*(uint16 *)&f19_enSpace.m_cursorY)
#define popupVisible (*(uint8 *)&f19_enSpace.m_popupVisible)
#define target1Scored (*(uint8 *)&f19_enSpace.m_target1Scored)
#define worldSamCount (*(int16 *)&f19_enSpace.m_worldSamCount)
#define word_2387A (*(int16 *)&f19_enSpace.m_word_2387A)
#define worldStringBuf ((char*)f19_enSpace.m_worldStringBuf)
#define missionScore (*(int32 *)&f19_enSpace.m_missionScore)
#define word_23B6A (*(int32 *)((uint8 *)&f19_enSpace.m_missionScore + 0))
#define target2Scored (*(uint8 *)&f19_enSpace.m_target2Scored)
#define popupY (*(int16 *)&f19_enSpace.m_popupY)
#define word_23C60 (*(int16 *)((uint8 *)&f19_enSpace.m_popupY + 0))
#define word_23C62 (*(int16 *)&f19_enSpace.m_word_23C62)
#define worldRouteCount (*(int16 *)&f19_enSpace.m_worldRouteCount)
#define word_23C6C (*(int16 *)&f19_enSpace.m_word_23C6C)
#define popupX (*(int16 *)&f19_enSpace.m_popupX)
#define word_23C72 (*(int16 *)&f19_enSpace.m_word_23C72)
#define word_23C74 (*(int16 *)&f19_enSpace.m_word_23C74)
#define word_23C76 (*(int16 *)&f19_enSpace.m_word_23C76)
#define word_23C78 (*(int16 *)&f19_enSpace.m_word_23C78)
#define word_23C7A (*(int16 *)&f19_enSpace.m_word_23C7A)
#define word_23C7C (*(int16 *)&f19_enSpace.m_word_23C7C)
#endif /* F19ENVARS_H */
