/* generated by tools/f19_deblob.py - real globals replacing the
   f19_dseg offset macros (EGAME.EXE data segment). */
#ifndef F19EGVARS_H
#define F19EGVARS_H
#include "inttype.h"
#include "f19seg.h"

extern int16 word_2EE72;
extern int16 word_2EE9C;
extern int8 byte_2EEE4;
extern int8 g_exitStatus;
extern int16 g_gfxModeUnset;
extern int32 off_2EEE8;
extern char g_colorPalettes[64];
extern const int16 f19d_g_dirGridOffsets[215];
extern const int16 g_lodObjectCount[6];
extern int16 g_lodGridDim[108];
extern uint16 f19d_sizes3dt[5];
extern uint16 f19d_matrix3dt[5][32];
extern uint16 f19d_g_modelOffsetTable[37];
extern uint8 g_theaterGrids[368];
extern const int16 g_mapTileLodTable[11];
extern uint8 f19d_colorLut[6562];
extern uint8 f19d_flt15_buf2[5626];
extern const int16 sinTable[751];
extern const uint8 rollOfsBase[538];
extern int16 tapeText0[11];
extern int16 tapeText1[11];
extern int16 tapeText2[11];
extern int16 tapeText3[11];
extern int16 sprite0[15];
extern int16 sprite1[15];
extern int16 sprite2[15];
extern int16 sprite3[44];
extern uint8 speedLabelBuf[6];
extern uint8 altLabelBuf[4];
extern uint8 f19d_digitStrip[176];
extern uint8 compassTape[522];
extern uint8 pitchLblTable[92];
extern uint8 tapeDrawStr[68];
extern uint8 f19d_joyAxes[58];
extern int8 g_geeTable[130];
extern int16 f19d_g_orientMatrix[9];
extern int16 f19d_g_yawMatrix[9];
extern int16 f19d_g_pitchMatrix[9];
extern int16 f19d_g_rollMatrix[9];
extern int16 f19d_g_matrixScratch[24];
extern int16 g_frontViewShape[11];
extern int16 g_rearViewShape[77];
extern int16 g_rightViewShape[37];
extern int16 g_leftViewShape[52];
extern int16 f19d_waypoints[10];
struct Weapon;
extern struct Weapon g_samSpecs[23];
struct ObjType;
extern struct ObjType g_objTypes[19];
struct Sam;
extern struct Sam f19d_sams[39];
extern int16 f19d_g_bombDamageMask;
extern int16 f19d_g_fuelRemaining;
extern int16 f19d_g_eventTimers[4];
struct MissileSpec;
extern struct MissileSpec f19d_missleSpec[1];
extern int16 f19d_g_frameRateScaling;
struct Missile;
extern struct Missile f19d_missiles[20];
extern int8 g_statTab[20][13];
struct FireRec;
extern struct FireRec g_fireRecs[1];
struct Particle;
extern struct Particle f19d_g_particles[8];
extern int16 f19d_g_smokeParticleSlot;
extern int16 g_maneuverTable[3][8][8];
struct Projectile;
extern struct Projectile f19d_g_projectiles[27];
struct StatCell;
extern struct StatCell g_statCells[19];
struct CellRect;
extern struct CellRect g_weaponCells[64];
extern int16 g_wpnSpriteX[4];
extern int16 g_wpnSpriteY[371];
extern char f19d_regnStr[62];
extern int16 f19d_g_axisInputAccum[882];
extern int16 f19d_flt15_buf1[311];
extern char g_nameBuf[90];
extern char geeStrBuf[44];
extern uint8 f19d_buf4_3dg[516];
extern uint8 f19d_buf3_3dg[1030];
extern uint8 f19d_buf2_3dg[598];
extern uint8 f19d_buf1_3dg[256];
extern uint8 f19d_buf_3dt[4002];
extern uint8 f19d_g_topLodGrid[72];
struct ViewSnapshot;
extern struct ViewSnapshot f19d_g_viewSnapshotRing[16];
extern int16 f19d_g_camRotMatrix[9];
struct MapTarget;
extern struct MapTarget f19d_g_planeTable[85];
extern int16 g_markerPosY;
extern int8 f19d_g_mapCellFlags[408];
extern int16 g_setupSlots[95];
struct SimObject;
extern struct SimObject f19d_g_simObjects[20];
extern int16 g_lockCooldown;
extern int16 f19d_g_threatRefX;
extern int32 f19d_g_camEyeY;
extern int16 f19d_g_wreckFallVel;
extern int16 f19d_g_liftForce;
extern int16 f19d_g_threatRefY;
extern int16 f19d_g_camEyeZ;
extern uint8 hercFlag;
extern int16 f19d_g_threatRefZ;
extern int16 f19d_g_viewRoll;
struct DynTileOverride;
extern struct DynTileOverride f19d_g_dynTileEntries[311];
extern int16 f19d_g_wreckX;
extern int16 f19d_g_waterTargetId[10];
extern int8 f19d_g_tileKillTally[104];
extern char g_hudMessageBuf[100];
extern int8 g_classTab[128];
extern int16 f19d_g_landTargetId[4];
extern char f19d_g_itoaScratch[236];
extern int8 f19d_g_stringPool[760];
extern uint16 f19d_matrix3dt_2[5][32];
extern int16 f19d_g_scopeClipBottom;
extern int16 f19d_g_pitchInput;
extern int16 f19d_g_cornerSpeed;
extern int16 word_38A12;
extern int16 f19d_g_viewHeading;
struct BulletTrack;
extern struct BulletTrack f19d_bulletTracks[33];
extern int16 f19d_size3d3_7;
#define byte_2EEE5 (*(int8 *)&g_exitStatus)
#define word_2EEE6 (*(int16 *)&g_gfxModeUnset)
#define word_2EF0A scenarioPlh[16]
#define word_2EF0C scenarioPlh[17]
#define word_2EF0E scenarioPlh[18]
#define word_2EF10 scenarioPlh[19]
#define byte_2EF12 (*(int8 *)((uint8 *)scenarioPlh + 40))
#define word_2F268 scenarioPlh[447]
#define byte_2F26A (*(int8 *)((uint8 *)scenarioPlh + 896))
#define word_2F464 g_lodObjectCount[5]
#define g_waypointNameBase g_lodGridDim[5]
#define word_2F470 g_lodGridDim[5]
#define word_2F53A g_lodGridDim[106]
#define word_2F6C8 f19d_g_modelOffsetTable[32]
#define word_2F6CA f19d_g_modelOffsetTable[33]
#define word_2F6CC f19d_g_modelOffsetTable[34]
#define word_2F6CE f19d_g_modelOffsetTable[35]
#define word_2F7D2 (*(int16 *)((uint8 *)g_theaterGrids + 256))
#define word_2F80C (*(int16 *)((uint8 *)g_theaterGrids + 314))
#define word_2F80E (*(int16 *)((uint8 *)g_theaterGrids + 316))
#define word_2F812 (*(int16 *)((uint8 *)g_theaterGrids + 320))
#define word_2F814 (*(int16 *)((uint8 *)g_theaterGrids + 322))
#define word_2F816 (*(int16 *)((uint8 *)g_theaterGrids + 324))
#define word_2F818 (*(int16 *)((uint8 *)g_theaterGrids + 326))
#define word_2F81A (*(int16 *)((uint8 *)g_theaterGrids + 328))
#define word_2F81C (*(int16 *)((uint8 *)g_theaterGrids + 330))
#define word_2F81E (*(int16 *)((uint8 *)g_theaterGrids + 332))
#define word_2F820 (*(int16 *)((uint8 *)g_theaterGrids + 334))
#define word_2F822 (*(int16 *)((uint8 *)g_theaterGrids + 336))
#define word_2F824 (*(int16 *)((uint8 *)g_theaterGrids + 338))
#define word_2F826 (*(int16 *)((uint8 *)g_theaterGrids + 340))
#define word_2F828 (*(int16 *)((uint8 *)g_theaterGrids + 342))
#define byte_2F82A g_theaterGrids[344]
#define byte_2F82B g_theaterGrids[345]
#define byte_2F82C g_theaterGrids[346]
#define word_2F82D (*(int16 *)((uint8 *)g_theaterGrids + 347))
#define word_2F82F (*(int16 *)((uint8 *)g_theaterGrids + 349))
#define word_2F831 (*(int16 *)((uint8 *)g_theaterGrids + 351))
#define word_2F833 (*(int16 *)((uint8 *)g_theaterGrids + 353))
#define word_2F835 (*(int16 *)((uint8 *)g_theaterGrids + 355))
#define word_2F837 (*(int16 *)((uint8 *)g_theaterGrids + 357))
#define word_2F839 (*(int16 *)((uint8 *)g_theaterGrids + 359))
#define word_2F83B (*(int16 *)((uint8 *)g_theaterGrids + 361))
#define word_2F84C g_mapTileLodTable[5]
#define word_2F84E g_mapTileLodTable[6]
#define word_2F850 g_mapTileLodTable[7]
#define byte_2F852 (*(int8 *)((uint8 *)g_mapTileLodTable + 16))
#define byte_2F853 (*(int8 *)((uint8 *)g_mapTileLodTable + 17))
#define word_2F854 g_mapTileLodTable[9]
#define byte_2F856 (*(int8 *)((uint8 *)g_mapTileLodTable + 20))
#define byte_2F85B f19d_colorLut[3]
#define word_2F870 (*(int16 *)((uint8 *)f19d_colorLut + 24))
#define word_2F872 (*(int16 *)((uint8 *)f19d_colorLut + 26))
#define word_2F874 (*(int16 *)((uint8 *)f19d_colorLut + 28))
#define word_2F876 (*(int16 *)((uint8 *)f19d_colorLut + 30))
#define word_2F878 (*(int16 *)((uint8 *)f19d_colorLut + 32))
#define dword_2F8F8 (*(int32 *)((uint8 *)f19d_colorLut + 160))
#define word_2F8FC (*(int16 *)((uint8 *)f19d_colorLut + 164))
#define word_2F8FE (*(int16 *)((uint8 *)f19d_colorLut + 166))
#define word_2F900 (*(int16 *)((uint8 *)f19d_colorLut + 168))
#define word_2F902 (*(int16 *)((uint8 *)f19d_colorLut + 170))
#define word_2F904 (*(int16 *)((uint8 *)f19d_colorLut + 172))
#define word_2F906 (*(int16 *)((uint8 *)f19d_colorLut + 174))
#define word_2F908 (*(int16 *)((uint8 *)f19d_colorLut + 176))
#define word_2F90A (*(int16 *)((uint8 *)f19d_colorLut + 178))
#define word_2F90C (*(int16 *)((uint8 *)f19d_colorLut + 180))
#define word_2F90E (*(int16 *)((uint8 *)f19d_colorLut + 182))
#define word_2F910 (*(int16 *)((uint8 *)f19d_colorLut + 184))
#define word_2F912 (*(int16 *)((uint8 *)f19d_colorLut + 186))
#define byte_2F914 f19d_colorLut[188]
#define word_2F91C (*(int16 *)((uint8 *)f19d_colorLut + 196))
#define word_2F91E (*(int16 *)((uint8 *)f19d_colorLut + 198))
#define word_2F920 (*(int16 *)((uint8 *)f19d_colorLut + 200))
#define word_2F922 (*(int16 *)((uint8 *)f19d_colorLut + 202))
#define word_2F924 (*(int16 *)((uint8 *)f19d_colorLut + 204))
#define word_2F926 (*(int16 *)((uint8 *)f19d_colorLut + 206))
#define word_2F928 (*(int16 *)((uint8 *)f19d_colorLut + 208))
#define word_2F92A (*(int16 *)((uint8 *)f19d_colorLut + 210))
#define word_2F92C (*(int16 *)((uint8 *)f19d_colorLut + 212))
#define word_2F92E (*(int16 *)((uint8 *)f19d_colorLut + 214))
#define word_2F930 (*(int16 *)((uint8 *)f19d_colorLut + 216))
#define word_2F932 (*(int16 *)((uint8 *)f19d_colorLut + 218))
#define word_2F934 (*(int16 *)((uint8 *)f19d_colorLut + 220))
#define word_2F936 (*(int16 *)((uint8 *)f19d_colorLut + 222))
#define word_2F938 (*(int16 *)((uint8 *)f19d_colorLut + 224))
#define word_2F93A (*(int16 *)((uint8 *)f19d_colorLut + 226))
#define word_2F93C (*(int16 *)((uint8 *)f19d_colorLut + 228))
#define word_2F93E (*(int16 *)((uint8 *)f19d_colorLut + 230))
#define word_2F940 (*(int16 *)((uint8 *)f19d_colorLut + 232))
#define word_2F942 (*(int16 *)((uint8 *)f19d_colorLut + 234))
#define word_2F944 (*(int16 *)((uint8 *)f19d_colorLut + 236))
#define word_2F946 (*(int16 *)((uint8 *)f19d_colorLut + 238))
#define word_2F948 (*(int16 *)((uint8 *)f19d_colorLut + 240))
#define word_2F94A (*(int16 *)((uint8 *)f19d_colorLut + 242))
#define word_2F94C (*(int16 *)((uint8 *)f19d_colorLut + 244))
#define word_2F94E (*(int16 *)((uint8 *)f19d_colorLut + 246))
#define word_2F950 (*(int16 *)((uint8 *)f19d_colorLut + 248))
#define word_2F952 (*(int16 *)((uint8 *)f19d_colorLut + 250))
#define word_2F954 (*(int16 *)((uint8 *)f19d_colorLut + 252))
#define word_2F956 (*(int16 *)((uint8 *)f19d_colorLut + 254))
#define word_2F958 (*(int16 *)((uint8 *)f19d_colorLut + 256))
#define word_2F95A (*(int16 *)((uint8 *)f19d_colorLut + 258))
#define word_2F95C (*(int16 *)((uint8 *)f19d_colorLut + 260))
#define word_2F95E (*(int16 *)((uint8 *)f19d_colorLut + 262))
#define word_2F960 (*(int16 *)((uint8 *)f19d_colorLut + 264))
#define word_2F962 (*(int16 *)((uint8 *)f19d_colorLut + 266))
#define word_2F964 (*(int16 *)((uint8 *)f19d_colorLut + 268))
#define word_2F966 (*(int16 *)((uint8 *)f19d_colorLut + 270))
#define word_2F968 (*(int16 *)((uint8 *)f19d_colorLut + 272))
#define word_2F96A (*(int16 *)((uint8 *)f19d_colorLut + 274))
#define word_2F96C (*(int16 *)((uint8 *)f19d_colorLut + 276))
#define byte_2F970 f19d_colorLut[280]
#define word_2F972 (*(int16 *)((uint8 *)f19d_colorLut + 282))
#define word_2F974 (*(int16 *)((uint8 *)f19d_colorLut + 284))
#define word_2F976 (*(int16 *)((uint8 *)f19d_colorLut + 286))
#define word_2F978 (*(int16 *)((uint8 *)f19d_colorLut + 288))
#define word_2F97A (*(int16 *)((uint8 *)f19d_colorLut + 290))
#define word_2FB58 (*(int16 *)((uint8 *)f19d_colorLut + 768))
#define word_2FB5A (*(int16 *)((uint8 *)f19d_colorLut + 770))
#define word_2FB5C (*(int16 *)((uint8 *)f19d_colorLut + 772))
#define word_2FB5E (*(int16 *)((uint8 *)f19d_colorLut + 774))
#define word_2FD3C (*(int16 *)((uint8 *)f19d_colorLut + 1252))
#define word_2FD3E (*(int16 *)((uint8 *)f19d_colorLut + 1254))
#define word_2FD40 (*(int16 *)((uint8 *)f19d_colorLut + 1256))
#define word_2FD42 (*(int16 *)((uint8 *)f19d_colorLut + 1258))
#define word_2FF20 (*(int16 *)((uint8 *)f19d_colorLut + 1736))
#define word_2FF22 (*(int16 *)((uint8 *)f19d_colorLut + 1738))
#define g_vprojX (*(int16 *)((uint8 *)f19d_colorLut + 1740))
#define g_vprojXlo (*(int16 *)((uint8 *)f19d_colorLut + 1740))
#define word_2FF24 (*(int16 *)((uint8 *)f19d_colorLut + 1740))
#define dword_30104 (*(int32 *)((uint8 *)f19d_colorLut + 2220))
#define g_vprojY (*(int16 *)((uint8 *)f19d_colorLut + 2224))
#define g_vprojYlo (*(int16 *)((uint8 *)f19d_colorLut + 2224))
#define word_30108 (*(int16 *)((uint8 *)f19d_colorLut + 2224))
#define dword_302E8 (*(int32 *)((uint8 *)f19d_colorLut + 2704))
#define unk_30BFB f19d_colorLut[5027]
#define unk_30C77 f19d_colorLut[5151]
#define unk_30E59 f19d_colorLut[5633]
#define unk_30FE4 f19d_colorLut[6028]
#define word_311B4 (*(int16 *)((uint8 *)f19d_colorLut + 6492))
#define word_3223A (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4160))
#define word_3223C (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4162))
#define word_3223E (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4164))
#define word_32240 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4166))
#define g_projClipFlag f19d_flt15_buf2[4168]
#define word_32242 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4168))
#define byte_32244 f19d_flt15_buf2[4170]
#define word_32245 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4171))
#define word_32247 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4173))
#define byte_3226A f19d_flt15_buf2[4208]
#define word_322CC (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4306))
#define word_322CE (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4308))
#define word_322D0 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4310))
#define byte_322D2 f19d_flt15_buf2[4312]
#define byte_322D3 f19d_flt15_buf2[4313]
#define byte_322D4 f19d_flt15_buf2[4314]
#define word_322D5 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4315))
#define word_322D7 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4317))
#define word_322D9 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4319))
#define word_322DB (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4321))
#define word_322DD (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4323))
#define word_322DF (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4325))
#define word_322E1 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4327))
#define word_322E3 (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4329))
#define byte_322ED f19d_flt15_buf2[4339]
#define byte_322EE f19d_flt15_buf2[4340]
#define word_322EF (*(int16 *)((uint8 *)f19d_flt15_buf2 + 4341))
#define byte_329FA (*(int8 *)((uint8 *)sinTable + 518))
#define word_329FB (*(int16 *)((uint8 *)sinTable + 519))
#define word_329FD (*(int16 *)((uint8 *)sinTable + 521))
#define word_329FF (*(int16 *)((uint8 *)sinTable + 523))
#define word_32A01 (*(int16 *)((uint8 *)sinTable + 525))
#define word_32A03 (*(int16 *)((uint8 *)sinTable + 527))
#define word_32A05 (*(int16 *)((uint8 *)sinTable + 529))
#define word_32A09 (*(int16 *)((uint8 *)sinTable + 533))
#define word_32A0B (*(int16 *)((uint8 *)sinTable + 535))
#define g_mapX sinTable[268]
#define word_32A0D (*(int16 *)((uint8 *)sinTable + 537))
#define word_32A0F (*(int16 *)((uint8 *)sinTable + 539))
#define unk_32A11 (*(int8 *)((uint8 *)sinTable + 541))
#define unk_32BC9 (*(int8 *)((uint8 *)sinTable + 981))
#define word_32D81 (*(int16 *)((uint8 *)sinTable + 1421))
#define word_32D83 (*(int16 *)((uint8 *)sinTable + 1423))
#define word_32D85 (*(int16 *)((uint8 *)sinTable + 1425))
#define word_32D87 (*(int16 *)((uint8 *)sinTable + 1427))
#define byte_32D8A (*(int8 *)((uint8 *)sinTable + 1430))
#define word_32D8B (*(int16 *)((uint8 *)sinTable + 1431))
#define word_32D8D (*(int16 *)((uint8 *)sinTable + 1433))
#define word_32D8F (*(int16 *)((uint8 *)sinTable + 1435))
#define word_32D91 (*(int16 *)((uint8 *)sinTable + 1437))
#define byte_32D94 (*(int8 *)((uint8 *)sinTable + 1440))
#define word_32D95 (*(int16 *)((uint8 *)sinTable + 1441))
#define word_32D97 (*(int16 *)((uint8 *)sinTable + 1443))
#define byte_32DA3 (*(int8 *)((uint8 *)sinTable + 1455))
#define byte_32DA4 (*(int8 *)((uint8 *)sinTable + 1456))
#define word_32DA5 (*(int16 *)((uint8 *)sinTable + 1457))
#define word_32DA7 (*(int16 *)((uint8 *)sinTable + 1459))
#define word_32DA9 (*(int16 *)((uint8 *)sinTable + 1461))
#define byte_32DAB (*(int8 *)((uint8 *)sinTable + 1463))
#define word_32DAC sinTable[732]
#define word_32DAE sinTable[733]
#define byte_32DB0 (*(int8 *)((uint8 *)sinTable + 1468))
#define byte_32DB1 (*(int8 *)((uint8 *)sinTable + 1469))
#define word_32DB2 sinTable[735]
#define word_32DB4 sinTable[736]
#define word_32DB6 sinTable[737]
#define word_32DB8 sinTable[738]
#define word_32DBA sinTable[739]
#define word_32DBC sinTable[740]
#define byte_32DBE (*(int8 *)((uint8 *)sinTable + 1482))
#define byte_32DBF (*(int8 *)((uint8 *)sinTable + 1483))
#define byte_32DC0 (*(int8 *)((uint8 *)sinTable + 1484))
#define word_32DC2 sinTable[743]
#define word_32DC4 sinTable[744]
#define word_32DC6 sinTable[745]
#define word_32DC8 sinTable[746]
#define word_32DCA sinTable[747]
#define byte_32DCC (*(int8 *)((uint8 *)sinTable + 1496))
#define byte_32DCD (*(int8 *)((uint8 *)sinTable + 1497))
#define byte_32DCE (*(int8 *)((uint8 *)sinTable + 1498))
#define word_32DD0 sinTable[750]
#define g_timerTick rollOfsBase[0]
#define byte_32DD2 rollOfsBase[0]
#define word_32FEC tapeText0[0]
#define word_32FF4 tapeText0[4]
#define word_32FF6 tapeText0[5]
#define word_32FF8 tapeText0[6]
#define word_32FFA tapeText0[7]
#define word_32FFC tapeText0[8]
#define word_33002 tapeText1[0]
#define word_3300A tapeText1[4]
#define word_3300C tapeText1[5]
#define word_3300E tapeText1[6]
#define word_33014 tapeText1[9]
#define word_33016 tapeText1[10]
#define word_33018 tapeText2[0]
#define word_33020 tapeText2[4]
#define word_33022 tapeText2[5]
#define word_33024 tapeText2[6]
#define word_33026 tapeText2[7]
#define word_3302A tapeText2[9]
#define word_3302C tapeText2[10]
#define word_3302E tapeText3[0]
#define word_33036 tapeText3[4]
#define word_33038 tapeText3[5]
#define word_3303A tapeText3[6]
#define word_33044 sprite0[0]
#define word_33048 sprite0[2]
#define word_3304A sprite0[3]
#define word_3304C sprite0[4]
#define word_3304E sprite0[5]
#define word_33050 sprite0[6]
#define word_33052 sprite0[7]
#define word_33062 sprite1[0]
#define word_33064 sprite1[1]
#define word_33066 sprite1[2]
#define word_33068 sprite1[3]
#define word_3306A sprite1[4]
#define word_3306C sprite1[5]
#define word_3306E sprite1[6]
#define word_33070 sprite1[7]
#define word_33080 sprite2[0]
#define word_33086 sprite2[3]
#define word_3309E sprite3[0]
#define word_330A4 sprite3[3]
#define byte_330BC (*(int8 *)((uint8 *)sprite3 + 30))
#define word_330BD (*(int16 *)((uint8 *)sprite3 + 31))
#define byte_330BF (*(int8 *)((uint8 *)sprite3 + 33))
#define word_330C0 sprite3[17]
#define byte_330C2 (*(int8 *)((uint8 *)sprite3 + 36))
#define word_330C3 (*(int16 *)((uint8 *)sprite3 + 37))
#define word_330C5 (*(int16 *)((uint8 *)sprite3 + 39))
#define word_330C7 (*(int16 *)((uint8 *)sprite3 + 41))
#define word_330C9 (*(int16 *)((uint8 *)sprite3 + 43))
#define word_330CB (*(int16 *)((uint8 *)sprite3 + 45))
#define word_330CD (*(int16 *)((uint8 *)sprite3 + 47))
#define word_330CF (*(int16 *)((uint8 *)sprite3 + 49))
#define word_330D1 (*(int16 *)((uint8 *)sprite3 + 51))
#define word_330D3 (*(int16 *)((uint8 *)sprite3 + 53))
#define word_330D5 (*(int16 *)((uint8 *)sprite3 + 55))
#define word_330D7 (*(int16 *)((uint8 *)sprite3 + 57))
#define byte_330D9 (*(int8 *)((uint8 *)sprite3 + 59))
#define word_330DA sprite3[30]
#define word_330DC sprite3[31]
#define word_330DE sprite3[32]
#define word_330E0 sprite3[33]
#define word_330E2 sprite3[34]
#define word_330E4 sprite3[35]
#define word_330E6 sprite3[36]
#define word_330E8 sprite3[37]
#define byte_330EA (*(int8 *)((uint8 *)sprite3 + 76))
#define word_330EB (*(int16 *)((uint8 *)sprite3 + 77))
#define word_330ED (*(int16 *)((uint8 *)sprite3 + 79))
#define word_330EF (*(int16 *)((uint8 *)sprite3 + 81))
#define word_330F1 (*(int16 *)((uint8 *)sprite3 + 83))
#define byte_330F3 (*(int8 *)((uint8 *)sprite3 + 85))
#define byte_330F4 (*(int8 *)((uint8 *)sprite3 + 86))
#define byte_330F5 (*(int8 *)((uint8 *)sprite3 + 87))
#define word_330F6 (*(int16 *)((uint8 *)speedLabelBuf + 0))
#define word_330F8 (*(int16 *)((uint8 *)speedLabelBuf + 2))
#define byte_330FB speedLabelBuf[5]
#define word_330FC (*(int16 *)((uint8 *)altLabelBuf + 0))
#define byte_33100 f19d_digitStrip[0]
#define byte_333B4 compassTape[516]
#define byte_333B5 compassTape[517]
#define word_333B6 (*(int16 *)((uint8 *)compassTape + 518))
#define word_333B8 (*(int16 *)((uint8 *)compassTape + 520))
#define word_33416 (*(int16 *)((uint8 *)tapeDrawStr + 0))
#define word_33418 (*(int16 *)((uint8 *)tapeDrawStr + 2))
#define word_3341A (*(int16 *)((uint8 *)tapeDrawStr + 4))
#define word_3341C (*(int16 *)((uint8 *)tapeDrawStr + 6))
#define word_3341E (*(int16 *)((uint8 *)tapeDrawStr + 8))
#define word_33420 (*(int16 *)((uint8 *)tapeDrawStr + 10))
#define word_33422 (*(int16 *)((uint8 *)tapeDrawStr + 12))
#define word_33424 (*(int16 *)((uint8 *)tapeDrawStr + 14))
#define word_33426 (*(int16 *)((uint8 *)tapeDrawStr + 16))
#define word_33428 (*(int16 *)((uint8 *)tapeDrawStr + 18))
#define word_33452 (*(int16 *)((uint8 *)tapeDrawStr + 60))
#define word_33454 (*(int16 *)((uint8 *)tapeDrawStr + 62))
#define byte_3345A f19d_joyAxes[0]
#define byte_3345B f19d_joyAxes[1]
#define byte_3345E f19d_joyAxes[4]
#define byte_3345F f19d_joyAxes[5]
#define word_33518 f19d_g_orientMatrix[1]
#define word_3351A f19d_g_orientMatrix[2]
#define word_3351C f19d_g_orientMatrix[3]
#define word_3351E f19d_g_orientMatrix[4]
#define word_33520 f19d_g_orientMatrix[5]
#define word_33526 f19d_g_orientMatrix[8]
#define word_33528 f19d_g_yawMatrix[0]
#define word_3352C f19d_g_yawMatrix[2]
#define word_33534 f19d_g_yawMatrix[6]
#define word_33538 f19d_g_yawMatrix[8]
#define word_33542 f19d_g_pitchMatrix[4]
#define word_33544 f19d_g_pitchMatrix[5]
#define word_33548 f19d_g_pitchMatrix[7]
#define word_3354A f19d_g_pitchMatrix[8]
#define word_3354C f19d_g_rollMatrix[0]
#define word_3354E f19d_g_rollMatrix[1]
#define word_33552 f19d_g_rollMatrix[3]
#define word_33554 f19d_g_rollMatrix[4]
#define word_33570 f19d_g_matrixScratch[9]
#define word_33572 f19d_g_matrixScratch[10]
#define word_33574 f19d_g_matrixScratch[11]
#define word_33576 f19d_g_matrixScratch[12]
#define word_33578 f19d_g_matrixScratch[13]
#define word_33580 f19d_g_matrixScratch[17]
#define byte_33582 (*(int8 *)((uint8 *)f19d_g_matrixScratch + 36))
#define byte_33585 (*(int8 *)((uint8 *)f19d_g_matrixScratch + 39))
#define g_engineThrust f19d_g_matrixScratch[21]
#define word_33588 f19d_g_matrixScratch[21]
#define word_3358A f19d_g_matrixScratch[22]
#define g_viewClipBottom f19d_g_matrixScratch[23]
#define word_3358C f19d_g_matrixScratch[23]
#define word_336F0 f19d_waypoints[0]
#define word_336F2 f19d_waypoints[1]
#define word_336F4 f19d_waypoints[2]
#define word_336F6 f19d_waypoints[3]
#define word_33700 f19d_waypoints[8]
#define g_wpSelectIdx f19d_waypoints[9]
#define word_33702 f19d_waypoints[9]
#define g_samRange (*(int16 *)((uint8 *)f19d_sams + 602))
#define word_33D00 (*(int16 *)((uint8 *)f19d_sams + 602))
#define g_samSpeed (*(int16 *)((uint8 *)f19d_sams + 604))
#define word_33D02 (*(int16 *)((uint8 *)f19d_sams + 604))
#define g_weaponMask (*(int8 *)((uint8 *)f19d_g_bombDamageMask + 0))
#define word_33D64 (*(int16 *)&f19d_g_bombDamageMask)
#define word_33D66 (*(int16 *)&f19d_g_fuelRemaining)
#define g_rocketCount f19d_g_eventTimers[1]
#define word_33D6A f19d_g_eventTimers[1]
#define g_chaffCount f19d_g_eventTimers[2]
#define word_33D6C f19d_g_eventTimers[2]
#define word_33D72 (*(int16 *)((uint8 *)f19d_missleSpec + 2))
#define word_33D80 (*(int16 *)((uint8 *)g_stores + 14))
#define word_33D82 (*(int16 *)((uint8 *)g_stores + 16))
#define word_33D84 (*(int16 *)((uint8 *)g_stores + 18))
#define word_33D86 (*(int16 *)((uint8 *)g_stores + 20))
#define g_isCampaignMission (*(int16 *)((uint8 *)g_stores + 22))
#define word_33D88 (*(int16 *)((uint8 *)g_stores + 22))
#define word_33D8A (*(int16 *)((uint8 *)g_stores + 24))
#define word_33D8C (*(int16 *)((uint8 *)g_stores + 26))
#define g_panelLabelOn (*(int16 *)((uint8 *)g_stores + 30))
#define word_33D90 (*(int16 *)((uint8 *)g_stores + 30))
#define word_33D92 (*(int16 *)&f19d_g_frameRateScaling)
#define word_340A0 (*(int16 *)((uint8 *)g_fireRecs + 0))
#define word_340A2 (*(int16 *)((uint8 *)g_fireRecs + 2))
#define word_340A8 (*(int16 *)((uint8 *)g_fireRecs + 8))
#define word_34110 (*(int16 *)&f19d_g_smokeParticleSlot)
#define word_343B2 (*(int16 *)((uint8 *)f19d_g_projectiles + 288))
#define word_343B4 (*(int16 *)((uint8 *)f19d_g_projectiles + 290))
#define word_343B6 (*(int16 *)((uint8 *)f19d_g_projectiles + 292))
#define word_343B8 (*(int16 *)((uint8 *)f19d_g_projectiles + 294))
#define word_343BA (*(int16 *)((uint8 *)f19d_g_projectiles + 296))
#define word_343BC (*(int16 *)((uint8 *)f19d_g_projectiles + 298))
#define g_selStoreState (*(int16 *)((uint8 *)f19d_g_projectiles + 300))
#define word_343BE (*(int16 *)((uint8 *)f19d_g_projectiles + 300))
#define word_343C0 (*(int16 *)((uint8 *)f19d_g_projectiles + 302))
#define word_343C2 (*(int16 *)((uint8 *)f19d_g_projectiles + 304))
#define g_selSimObj (*(int16 *)((uint8 *)f19d_g_projectiles + 306))
#define word_343C4 (*(int16 *)((uint8 *)f19d_g_projectiles + 306))
#define word_343C6 (*(int16 *)((uint8 *)f19d_g_projectiles + 308))
#define word_343C8 (*(int16 *)((uint8 *)f19d_g_projectiles + 310))
#define word_343CA (*(int16 *)((uint8 *)f19d_g_projectiles + 312))
#define word_343CC (*(int16 *)((uint8 *)f19d_g_projectiles + 314))
#define word_343CE (*(int16 *)((uint8 *)f19d_g_projectiles + 316))
#define g_timeAccelMode (*(uint16 *)((uint8 *)f19d_g_projectiles + 318))
#define word_343D0 (*(int16 *)((uint8 *)f19d_g_projectiles + 318))
#define word_343D2 (*(int16 *)((uint8 *)f19d_g_projectiles + 320))
#define word_34646 (*(int16 *)((uint8 *)g_weaponCells + 110))
#define word_3465E (*(int16 *)((uint8 *)g_weaponCells + 134))
#define word_34676 (*(int16 *)((uint8 *)g_weaponCells + 158))
#define word_3468E (*(int16 *)((uint8 *)g_weaponCells + 182))
#define word_346A6 (*(int16 *)((uint8 *)g_weaponCells + 206))
#define word_346A8 (*(int16 *)((uint8 *)g_weaponCells + 208))
#define word_346AA (*(int16 *)((uint8 *)g_weaponCells + 210))
#define word_346AC (*(int16 *)((uint8 *)g_weaponCells + 212))
#define word_346AE (*(int16 *)((uint8 *)g_weaponCells + 214))
#define word_346B0 (*(int16 *)((uint8 *)g_weaponCells + 216))
#define word_346B2 (*(int16 *)((uint8 *)g_weaponCells + 218))
#define word_346B4 (*(int16 *)((uint8 *)g_weaponCells + 220))
#define word_346B6 (*(int16 *)((uint8 *)g_weaponCells + 222))
#define word_346C6 (*(int16 *)((uint8 *)g_weaponCells + 238))
#define word_346C8 (*(int16 *)((uint8 *)g_weaponCells + 240))
#define word_346CA (*(int16 *)((uint8 *)g_weaponCells + 242))
#define word_346CC (*(int16 *)((uint8 *)g_weaponCells + 244))
#define word_346CE (*(int16 *)((uint8 *)g_weaponCells + 246))
#define word_346D0 (*(int16 *)((uint8 *)g_weaponCells + 248))
#define word_346D2 (*(int16 *)((uint8 *)g_weaponCells + 250))
#define word_346D4 (*(int16 *)((uint8 *)g_weaponCells + 252))
#define g_tapeClipX (*(int16 *)((uint8 *)g_weaponCells + 256))
#define word_346D8 (*(int16 *)((uint8 *)g_weaponCells + 256))
#define byte_346DE (*(int8 *)((uint8 *)g_weaponCells + 262))
#define byte_346DF (*(int8 *)((uint8 *)g_weaponCells + 263))
#define word_346E4 (*(int16 *)((uint8 *)g_weaponCells + 268))
#define word_346E6 (*(int16 *)((uint8 *)g_weaponCells + 270))
#define word_346E8 (*(int16 *)((uint8 *)g_weaponCells + 272))
#define word_346EA (*(int16 *)((uint8 *)g_weaponCells + 274))
#define word_346EC (*(int16 *)((uint8 *)g_weaponCells + 276))
#define g_lgbCount g_wpnSpriteY[230]
#define word_349AC g_wpnSpriteY[230]
#define g_lgbTimer g_wpnSpriteY[231]
#define word_349AE g_wpnSpriteY[231]
#define g_lockMark g_wpnSpriteY[232]
#define word_349B0 g_wpnSpriteY[232]
#define byte_34AC4 (*(int8 *)((uint8 *)g_wpnSpriteY + 740))
#define word_34AFE (*(int16 *)((uint8 *)f19d_regnStr + 56))
#define g_joySensitivity (*(int16 *)((uint8 *)f19d_regnStr + 58))
#define word_34B00 (*(int16 *)((uint8 *)f19d_regnStr + 58))
#define word_34B02 (*(int16 *)((uint8 *)f19d_regnStr + 60))
#define word_34B04 f19d_g_axisInputAccum[0]
#define word_34B06 f19d_g_axisInputAccum[1]
#define g_soundPriorityFloor f19d_g_axisInputAccum[2]
#define word_34B08 f19d_g_axisInputAccum[2]
#define g_smokeTimer f19d_g_axisInputAccum[3]
#define word_34B0A f19d_g_axisInputAccum[3]
#define byte_34B0C (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 8))
#define byte_34B0D (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 9))
#define word_34D70 f19d_g_axisInputAccum[310]
#define word_34D72 f19d_g_axisInputAccum[311]
#define word_34D76 f19d_g_axisInputAccum[313]
#define word_34D78 f19d_g_axisInputAccum[314]
#define word_34EBA f19d_g_axisInputAccum[475]
#define word_34EBC f19d_g_axisInputAccum[476]
#define word_34EBE f19d_g_axisInputAccum[477]
#define word_34EC2 f19d_g_axisInputAccum[479]
#define word_34EC4 f19d_g_axisInputAccum[480]
#define word_34EC6 f19d_g_axisInputAccum[481]
#define word_34EC8 f19d_g_axisInputAccum[482]
#define off_34ECA (*(int32 *)((uint8 *)f19d_g_axisInputAccum + 966))
#define word_34ECC f19d_g_axisInputAccum[484]
#define word_34F1C f19d_g_axisInputAccum[524]
#define dword_34F2B (*(int32 *)((uint8 *)f19d_g_axisInputAccum + 1063))
#define word_34F37 (*(int16 *)((uint8 *)f19d_g_axisInputAccum + 1075))
#define word_34F39 (*(int16 *)((uint8 *)f19d_g_axisInputAccum + 1077))
#define word_34F3D (*(int16 *)((uint8 *)f19d_g_axisInputAccum + 1081))
#define word_34F3F (*(int16 *)((uint8 *)f19d_g_axisInputAccum + 1083))
#define byte_34F42 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1086))
#define word_34F44 f19d_g_axisInputAccum[544]
#define word_34F5E f19d_g_axisInputAccum[557]
#define word_34F60 f19d_g_axisInputAccum[558]
#define seg_34F62 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1118))
#define byte_34F68 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1124))
#define byte_34F69 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1125))
#define dword_34F6A (*(int32 *)((uint8 *)f19d_g_axisInputAccum + 1126))
#define word_34F6E f19d_g_axisInputAccum[565]
#define word_34F70 f19d_g_axisInputAccum[566]
#define word_34F72 f19d_g_axisInputAccum[567]
#define word_34F8C f19d_g_axisInputAccum[580]
#define word_350A6 f19d_g_axisInputAccum[721]
#define byte_350A9 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1445))
#define word_350AA f19d_g_axisInputAccum[723]
#define word_350AC f19d_g_axisInputAccum[724]
#define word_350B0 f19d_g_axisInputAccum[726]
#define word_350B4 f19d_g_axisInputAccum[728]
#define word_350B8 f19d_g_axisInputAccum[730]
#define word_350BA f19d_g_axisInputAccum[731]
#define byte_350BE (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1466))
#define word_350C0 f19d_g_axisInputAccum[734]
#define word_350C2 f19d_g_axisInputAccum[735]
#define word_350C4 f19d_g_axisInputAccum[736]
#define unk_350C8 (*(int8 *)((uint8 *)f19d_g_axisInputAccum + 1476))
#define word_350CA f19d_g_axisInputAccum[739]
#define dword_350CC (*(int32 *)((uint8 *)f19d_g_axisInputAccum + 1480))
#define dword_350D0 (*(int32 *)((uint8 *)f19d_g_axisInputAccum + 1484))
#define word_351B0 f19d_g_axisInputAccum[854]
#define word_351B2 f19d_g_axisInputAccum[855]
#define word_351B4 f19d_g_axisInputAccum[856]
#define word_351B6 f19d_g_axisInputAccum[857]
#define word_351B8 f19d_g_axisInputAccum[858]
#define word_351BA f19d_g_axisInputAccum[859]
#define word_351BC f19d_g_axisInputAccum[860]
#define word_351BE f19d_g_axisInputAccum[861]
#define word_351C0 f19d_g_axisInputAccum[862]
#define word_351C2 f19d_g_axisInputAccum[863]
#define g_replayCount f19d_g_axisInputAccum[864]
#define word_351C4 f19d_g_axisInputAccum[864]
#define word_351C6 f19d_g_axisInputAccum[865]
#define word_351C8 f19d_g_axisInputAccum[866]
#define word_351CA f19d_g_axisInputAccum[867]
#define word_351CC f19d_g_axisInputAccum[868]
#define word_351CE f19d_g_axisInputAccum[869]
#define word_351D0 f19d_g_axisInputAccum[870]
#define g_targetLock f19d_g_axisInputAccum[874]
#define word_351D8 f19d_g_axisInputAccum[874]
#define word_351DA f19d_g_axisInputAccum[875]
#define g_aimClipSave f19d_g_axisInputAccum[876]
#define word_351DC f19d_g_axisInputAccum[876]
#define word_351DE f19d_g_axisInputAccum[877]
#define word_351E0 f19d_g_axisInputAccum[878]
#define word_351E2 f19d_g_axisInputAccum[879]
#define word_351E4 f19d_g_axisInputAccum[880]
#define word_35228 f19d_flt15_buf1[32]
#define word_3522A f19d_flt15_buf1[33]
#define word_3522C f19d_flt15_buf1[34]
#define word_3522E f19d_flt15_buf1[35]
#define word_35230 f19d_flt15_buf1[36]
#define word_35232 f19d_flt15_buf1[37]
#define word_35234 f19d_flt15_buf1[38]
#define word_35236 f19d_flt15_buf1[39]
#define word_35238 f19d_flt15_buf1[40]
#define word_3523A f19d_flt15_buf1[41]
#define word_3523C f19d_flt15_buf1[42]
#define byte_3523E (*(int8 *)((uint8 *)f19d_flt15_buf1 + 86))
#define byte_3523F (*(int8 *)((uint8 *)f19d_flt15_buf1 + 87))
#define byte_35240 (*(int8 *)((uint8 *)f19d_flt15_buf1 + 88))
#define byte_35241 (*(int8 *)((uint8 *)f19d_flt15_buf1 + 89))
#define word_35242 f19d_flt15_buf1[45]
#define word_35244 f19d_flt15_buf1[46]
#define word_35246 f19d_flt15_buf1[47]
#define byte_35248 (*(int8 *)((uint8 *)f19d_flt15_buf1 + 96))
#define byte_35249 (*(int8 *)((uint8 *)f19d_flt15_buf1 + 97))
#define word_3524A f19d_flt15_buf1[49]
#define byte_3524C (*(int8 *)((uint8 *)f19d_flt15_buf1 + 100))
#define word_35450 f19d_flt15_buf1[308]
#define word_35452 f19d_flt15_buf1[309]
#define word_35454 f19d_flt15_buf1[310]
#define byte_35456 g_nameBuf[0]
#define byte_3546E g_nameBuf[24]
#define byte_3546F g_nameBuf[25]
#define word_354A6 (*(int16 *)((uint8 *)g_nameBuf + 80))
#define word_354A8 (*(int16 *)((uint8 *)g_nameBuf + 82))
#define word_354AC (*(int16 *)((uint8 *)g_nameBuf + 86))
#define word_354AE (*(int16 *)((uint8 *)g_nameBuf + 88))
#define word_354BA (*(int16 *)((uint8 *)geeStrBuf + 10))
#define word_354BC (*(int16 *)((uint8 *)geeStrBuf + 12))
#define word_354BE (*(int16 *)((uint8 *)geeStrBuf + 14))
#define word_354C0 (*(int16 *)((uint8 *)geeStrBuf + 16))
#define dword_354C2 (*(int32 *)((uint8 *)geeStrBuf + 18))
#define word_354C6 (*(int16 *)((uint8 *)geeStrBuf + 22))
#define word_354C8 (*(int16 *)((uint8 *)geeStrBuf + 24))
#define word_354CA (*(int16 *)((uint8 *)geeStrBuf + 26))
#define word_354CC (*(int16 *)((uint8 *)geeStrBuf + 28))
#define word_354CE (*(int16 *)((uint8 *)geeStrBuf + 30))
#define dword_354D0 (*(int32 *)((uint8 *)geeStrBuf + 32))
#define g_camSavedRoll (*(int16 *)((uint8 *)geeStrBuf + 36))
#define word_354D4 (*(int16 *)((uint8 *)geeStrBuf + 36))
#define word_354D6 (*(int16 *)((uint8 *)geeStrBuf + 38))
#define g_threatProxX (*(int16 *)((uint8 *)geeStrBuf + 40))
#define word_354D8 (*(int16 *)((uint8 *)geeStrBuf + 40))
#define word_354DA (*(int16 *)((uint8 *)geeStrBuf + 42))
#define g_geeShakeToggle (*(int16 *)((uint8 *)f19d_buf4_3dg + 100))
#define word_356DC (*(int16 *)((uint8 *)f19d_buf4_3dg + 512))
#define g_threatProxY (*(int16 *)((uint8 *)f19d_buf4_3dg + 514))
#define word_356DE (*(int16 *)((uint8 *)f19d_buf4_3dg + 514))
#define word_358E0 (*(int16 *)((uint8 *)f19d_buf3_3dg + 512))
#define word_35AE2 (*(int16 *)((uint8 *)f19d_buf3_3dg + 1026))
#define word_35AE4 (*(int16 *)((uint8 *)f19d_buf3_3dg + 1028))
#define word_35CE6 (*(int16 *)((uint8 *)f19d_buf2_3dg + 512))
#define word_35D38 (*(int16 *)((uint8 *)f19d_buf2_3dg + 594))
#define byte_35D3A f19d_buf2_3dg[596]
#define word_36DDC (*(int16 *)((uint8 *)f19d_buf_3dt + 4000))
#define word_36E1E (*(int16 *)((uint8 *)f19d_g_topLodGrid + 64))
#define g_startRange (*(int16 *)((uint8 *)f19d_g_topLodGrid + 68))
#define word_36E22 (*(int16 *)((uint8 *)f19d_g_topLodGrid + 68))
#define word_36E24 (*(int16 *)((uint8 *)f19d_g_topLodGrid + 70))
#define g_selGridX (*(int16 *)((uint8 *)f19d_g_planeTable + 2))
#define word_36F3A (*(int16 *)((uint8 *)f19d_g_planeTable + 2))
#define g_selGridY (*(int16 *)((uint8 *)f19d_g_planeTable + 4))
#define word_36F3C (*(int16 *)((uint8 *)f19d_g_planeTable + 4))
#define g_selTileId (*(int16 *)((uint8 *)f19d_g_planeTable + 14))
#define word_36F46 (*(int16 *)((uint8 *)f19d_g_planeTable + 14))
#define g_mapExtentX (*(int16 *)((uint8 *)f19d_g_planeTable + 178))
#define word_36FEA (*(int16 *)((uint8 *)f19d_g_planeTable + 178))
#define g_mapExtentY (*(int16 *)((uint8 *)f19d_g_planeTable + 180))
#define word_36FEC (*(int16 *)((uint8 *)f19d_g_planeTable + 180))
#define word_373E8 (*(int16 *)((uint8 *)f19d_g_planeTable + 1200))
#define g_markerPosX (*(int16 *)((uint8 *)f19d_g_planeTable + 1202))
#define word_373EA (*(int16 *)((uint8 *)f19d_g_planeTable + 1202))
#define word_373EC (*(int16 *)((uint8 *)f19d_g_planeTable + 1204))
#define word_37484 (*(int16 *)((uint8 *)f19d_g_planeTable + 1356))
#define word_37486 (*(int16 *)((uint8 *)f19d_g_planeTable + 1358))
#define word_37488 (*(int16 *)&g_markerPosY)
#define word_3758A (*(int16 *)((uint8 *)f19d_g_mapCellFlags + 256))
#define g_missionStage g_setupSlots[0]
#define word_37622 g_setupSlots[0]
#define word_37624 g_setupSlots[1]
#define g_selStoreIdx g_setupSlots[2]
#define word_37626 g_setupSlots[2]
#define word_3762A g_setupSlots[4]
#define word_37634 g_setupSlots[9]
#define word_37636 g_setupSlots[10]
#define g_homeBaseIdx g_setupSlots[11]
#define word_37638 g_setupSlots[11]
#define word_3763C g_setupSlots[13]
#define word_376DC g_setupSlots[93]
#define word_376DE g_setupSlots[94]
#define word_379B0 (*(int16 *)&g_lockCooldown)
#define word_379B2 (*(int16 *)&f19d_g_threatRefX)
#define word_379B4 (*(int16 *)((uint8 *)f19d_g_camEyeY + 0))
#define word_379B6 (*(int16 *)((uint8 *)f19d_g_camEyeY + 2))
#define word_379B8 (*(int16 *)&f19d_g_wreckFallVel)
#define word_379BA (*(int16 *)&f19d_g_liftForce)
#define word_379BC (*(int16 *)&f19d_g_threatRefY)
#define word_379BE (*(int16 *)&f19d_g_camEyeZ)
#define byte_379C0 (*(int8 *)&hercFlag)
#define word_379C2 (*(int16 *)&f19d_g_threatRefZ)
#define word_379C4 (*(int16 *)&f19d_g_viewRoll)
#define g_wpPanelMode (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 240))
#define word_37AB6 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 240))
#define g_worldX (*(int32 *)((uint8 *)f19d_g_dynTileEntries + 724))
#define word_37CB8 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 754))
#define word_37CBA (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 756))
#define word_37CBC (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 758))
#define word_37CBE (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 760))
#define word_37CC0 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 762))
#define word_37CC2 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 764))
#define word_37CC4 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 766))
#define word_37CC6 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 768))
#define word_37CC8 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 770))
#define byte_37CCA (*(int8 *)((uint8 *)f19d_g_dynTileEntries + 772))
#define byte_37CCB (*(int8 *)((uint8 *)f19d_g_dynTileEntries + 773))
#define byte_37CCC (*(int8 *)((uint8 *)f19d_g_dynTileEntries + 774))
#define byte_37CCD (*(int8 *)((uint8 *)f19d_g_dynTileEntries + 775))
#define g_worldY (*(int32 *)((uint8 *)f19d_g_dynTileEntries + 2288))
#define word_382D4 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2318))
#define word_382D6 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2320))
#define word_382D8 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2322))
#define word_3831A (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2388))
#define g_camExtFlag (*(int8 *)((uint8 *)f19d_g_dynTileEntries + 2442))
#define word_3836C (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2470))
#define word_3836E (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2472))
#define word_38370 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2474))
#define word_38372 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2476))
#define word_38374 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2478))
#define word_38378 (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2482))
#define word_3837A (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2484))
#define word_3837C (*(int16 *)((uint8 *)f19d_g_dynTileEntries + 2486))
#define word_3837E (*(int16 *)&f19d_g_wreckX)
#define g_airTargetMark (*(int8 *)((uint8 *)f19d_g_waterTargetId + 0))
#define byte_38380 (*(int8 *)((uint8 *)f19d_g_waterTargetId + 0))
#define g_camSavedHead f19d_g_waterTargetId[1]
#define word_38382 f19d_g_waterTargetId[1]
#define word_38384 f19d_g_waterTargetId[2]
#define word_38388 f19d_g_waterTargetId[4]
#define word_3838A f19d_g_waterTargetId[5]
#define word_3838C f19d_g_waterTargetId[6]
#define g_storeDefCount f19d_g_waterTargetId[7]
#define word_3838E f19d_g_waterTargetId[7]
#define word_38390 f19d_g_waterTargetId[8]
#define word_38392 f19d_g_waterTargetId[9]
#define word_383F8 (*(int16 *)((uint8 *)f19d_g_tileKillTally + 100))
#define word_383FA (*(int16 *)((uint8 *)f19d_g_tileKillTally + 102))
#define word_3844C (*(int16 *)((uint8 *)g_hudMessageBuf + 80))
#define byte_3844E g_hudMessageBuf[82]
#define byte_3844F g_hudMessageBuf[83]
#define byte_38451 g_hudMessageBuf[85]
#define word_38452 (*(int16 *)((uint8 *)g_hudMessageBuf + 86))
#define word_38454 (*(int16 *)((uint8 *)g_hudMessageBuf + 88))
#define word_3845C (*(int16 *)((uint8 *)g_hudMessageBuf + 96))
#define word_3845E (*(int16 *)((uint8 *)g_hudMessageBuf + 98))
#define word_384C4 (*(int16 *)((uint8 *)g_classTab + 100))
#define g_missionTimeLimit (*(int16 *)((uint8 *)g_classTab + 102))
#define word_384C6 (*(int16 *)((uint8 *)g_classTab + 102))
#define word_384C8 (*(int16 *)((uint8 *)g_classTab + 104))
#define flagFarToNear (*(int16 *)((uint8 *)g_classTab + 106))
#define word_384CA (*(int16 *)((uint8 *)g_classTab + 106))
#define word_384CC (*(int16 *)((uint8 *)g_classTab + 108))
#define g_keyCode (*(int16 *)((uint8 *)g_classTab + 110))
#define word_384CE (*(int16 *)((uint8 *)g_classTab + 110))
#define word_384D0 (*(int16 *)((uint8 *)g_classTab + 112))
#define word_384D2 (*(int16 *)((uint8 *)g_classTab + 114))
#define word_384D4 (*(int16 *)((uint8 *)g_classTab + 116))
#define word_384D6 (*(int16 *)((uint8 *)g_classTab + 118))
#define word_384D8 (*(int16 *)((uint8 *)g_classTab + 120))
#define word_384DC (*(int16 *)((uint8 *)g_classTab + 124))
#define word_384DE (*(int16 *)((uint8 *)g_classTab + 126))
#define g_gndTargetMark (*(int8 *)((uint8 *)f19d_g_landTargetId + 0))
#define byte_384E0 (*(int8 *)((uint8 *)f19d_g_landTargetId + 0))
#define word_384E2 f19d_g_landTargetId[1]
#define word_384E4 f19d_g_landTargetId[2]
#define word_384E6 f19d_g_landTargetId[3]
#define word_384F4 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 12))
#define word_384F6 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 14))
#define word_384F8 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 16))
#define word_384FA (*(int16 *)((uint8 *)f19d_g_itoaScratch + 18))
#define g_liveObjCount (*(int16 *)((uint8 *)f19d_g_itoaScratch + 20))
#define word_384FC (*(int16 *)((uint8 *)f19d_g_itoaScratch + 20))
#define word_384FE (*(int16 *)((uint8 *)f19d_g_itoaScratch + 22))
#define word_38500 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 24))
#define word_38502 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 26))
#define word_38504 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 28))
#define word_38506 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 30))
#define g_curPanelMode (*(int16 *)((uint8 *)f19d_g_itoaScratch + 230))
#define word_385CE (*(int16 *)((uint8 *)f19d_g_itoaScratch + 230))
#define word_385D0 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 232))
#define word_385D2 (*(int16 *)((uint8 *)f19d_g_itoaScratch + 234))
#define word_388C2 (*(int16 *)((uint8 *)f19d_g_stringPool + 750))
#define word_388C4 (*(int16 *)((uint8 *)f19d_g_stringPool + 752))
#define word_388C6 (*(int16 *)((uint8 *)f19d_g_stringPool + 754))
#define word_388C8 (*(int16 *)((uint8 *)f19d_g_stringPool + 756))
#define g_drawPage f19d_g_stringPool[758]
#define byte_388CA f19d_g_stringPool[758]
#define word_38A0C (*(int16 *)&f19d_g_scopeClipBottom)
#define word_38A0E (*(int16 *)&f19d_g_pitchInput)
#define word_38A10 (*(int16 *)&f19d_g_cornerSpeed)
#define word_38A14 (*(int16 *)&f19d_g_viewHeading)
#define word_38B06 (*(int16 *)((uint8 *)f19d_bulletTracks + 240))
#define word_38B08 (*(int16 *)((uint8 *)f19d_bulletTracks + 242))
#define byte_38B0A (*(int8 *)((uint8 *)f19d_bulletTracks + 244))
#define word_38B0C (*(int16 *)((uint8 *)f19d_bulletTracks + 246))
#define word_38B0E (*(int16 *)((uint8 *)f19d_bulletTracks + 248))
#define dword_38B10 (*(int32 *)((uint8 *)f19d_bulletTracks + 250))
#define word_38B14 (*(int16 *)((uint8 *)f19d_bulletTracks + 254))
#define word_38B16 (*(int16 *)((uint8 *)f19d_bulletTracks + 256))
#define g_commEventFlag (*(int8 *)((uint8 *)f19d_bulletTracks + 770))
#define byte_38D18 (*(int8 *)((uint8 *)f19d_bulletTracks + 770))
#define g_scanDir (*(int16 *)((uint8 *)f19d_bulletTracks + 772))
#define word_38D1A (*(int16 *)((uint8 *)f19d_bulletTracks + 772))
#define word_38D1C (*(int16 *)((uint8 *)f19d_bulletTracks + 774))
#define word_38D1E (*(int16 *)((uint8 *)f19d_bulletTracks + 776))
#define word_38D20 (*(int16 *)((uint8 *)f19d_bulletTracks + 778))
#define word_38D22 (*(int16 *)((uint8 *)f19d_bulletTracks + 780))
#define word_38D24 (*(int16 *)((uint8 *)f19d_bulletTracks + 782))
#define word_38D26 (*(int16 *)((uint8 *)f19d_bulletTracks + 784))
#define g_savedGfxOvl (*(int16 *)((uint8 *)f19d_bulletTracks + 786))
#define word_38D28 (*(int16 *)((uint8 *)f19d_bulletTracks + 786))
#define word_38D2A (*(int16 *)((uint8 *)f19d_bulletTracks + 788))
#define word_38D2C (*(int16 *)((uint8 *)f19d_bulletTracks + 790))
#define word_38D2E (*(int16 *)&f19d_size3d3_7)
#define g_stores ((int16 (*)[2])((uint8 *)f19d_missleSpec + 2))
#define g_wpnSlots ((struct WSlot *)((uint8 *)g_fireRecs + 6))

extern const struct F19SegObj f19_egObjs[];
extern const int f19_egObjCount;
void f19_egVarsReset(void);
#endif
