/* generated by tools/f19_deblob.py - see f19stvars.h */
#include "f19stvars.h"
#include <string.h>
extern const uint8 f19_dseg_img[];

struct F19STData f19_stSpace;

/* image bytes cover [0,0x98E0); the rest is DOS BSS (zero). */
void f19_stVarsReset(void) {
    memcpy(&f19_stSpace, f19_dseg_img, 39136);
    memset((char *)&f19_stSpace + 39136, 0, sizeof f19_stSpace - 39136);
}

typedef char f19_stLayoutChk[(sizeof f19_stSpace) == 0x10000 ? 1 : -1];
