/* generated by tools/f19_deblob.py - named globals replacing the   f19_dseg blob (START.EXE data segment).  All dseg cells are members   of one packed struct at their exact DOS offsets, so indexed and   overlapping accesses see contiguous DOS-ordered storage. */
#ifndef F19STVARS_H
#define F19STVARS_H
#include "inttype.h"
#include "f19seg.h"

#pragma pack(push, 1)
struct F19STData {
    uint8 f19_stgap_0[230];   /* gap */      /* 0x00000 */
    int16 m_word_200E6;                      /* 0x000E6 */
    uint8 f19_stgap_E8[366];   /* gap */     /* 0x000E8 */
    uint16 m_typeNameTab[22];                /* 0x00256 */
    char m_str282[1076];                     /* 0x00282 */
    int16 m_statT1[414];                     /* 0x006B6 */
    uint32 m_esTable[564];                   /* 0x009F2 */
    int8 m_byte_212C2[1110];                 /* 0x012C2 */
    int16 m_word_21718[1543];                /* 0x01718 */
    uint8 m_clipTable[2457];                 /* 0x02326 */
    uint8 f19_stgap_2CBF[63];   /* gap */    /* 0x02CBF */
    uint8 m_g_flagTable2CFE[3766];           /* 0x02CFE */
    int16 m_gridLevelSize[6];                /* 0x03BB4 */
    uint16 m_terrainBuf1[5];                 /* 0x03BC0 */
    uint8 m_terrainTileCounts[576];          /* 0x03BCA */
    uint16 m_missionMidX[10];                /* 0x03E0A */
    char m_strTab14[1][14];                  /* 0x03E1E */
    uint8 f19_stgap_3E2C[308];   /* gap */   /* 0x03E2C */
    char m_strTab32[1][32];                  /* 0x03F60 */
    uint8 f19_stgap_3F80[584];   /* gap */   /* 0x03F80 */
    int16 m_siteTypeParms[347];              /* 0x041C8 */
    uint8 m_f19_linkTab[136];                /* 0x0447E */
    int16 m_missionSpeedTab[248];            /* 0x04506 */
    uint8 m_loadoutTab[1046];                /* 0x046F6 */
    uint8 m_f19_siteParms[672];              /* 0x04B0C */
    uint16 m_regnPlhPtr;                     /* 0x04DAC */
    uint16 m_plhFiles[4];                    /* 0x04DAE */
    char m_briefTimeA[6];                    /* 0x04DB6 */
    char m_briefTimeB[6];                    /* 0x04DBC */
    char m_briefTimeC[6];                    /* 0x04DC2 */
    char m_briefCoord2[1636];                /* 0x04DC8 */
    int16 m_word_2542C[20];                  /* 0x0542C */
    uint16 m_word_25454[20];                 /* 0x05454 */
    int16 m_word_2547C[2];                   /* 0x0547C */
    int16 m_word_25480[337];                 /* 0x05480 */
    int16 m_word_25722[10][25];              /* 0x05722 */
    uint8 f19_stgap_5916[4];   /* gap */     /* 0x05916 */
    int16 m_word_2591A;                      /* 0x0591A */
    uint16 m_word_2591C[7];                  /* 0x0591C */
    uint16 m_word_2592A[3];                  /* 0x0592A */
    int16 m_blinkColors[267];                /* 0x05930 */
    int16 m_word_25B46[258];                 /* 0x05B46 */
    int16 m_selInitTab[173];                 /* 0x05D4A */
    uint8 m_menuSelTab[300];                 /* 0x05EA4 */
    uint8 f19_stgap_5FD0[12];   /* gap */    /* 0x05FD0 */
    uint8 m_menuSelTab2[150];                /* 0x05FDC */
    uint8 f19_stgap_6072[8];   /* gap */     /* 0x06072 */
    uint16 m_word_2607A;                     /* 0x0607A */
    uint8 f19_stgap_607C[22];   /* gap */    /* 0x0607C */
    uint16 m_word_26092;                     /* 0x06092 */
    int16 m_initTab2[183];                   /* 0x06094 */
    uint8 m_menuSelTab3[250];                /* 0x06202 */
    uint8 f19_stgap_62FC[12];   /* gap */    /* 0x062FC */
    uint8 m_menuSelTab4[250];                /* 0x06308 */
    uint8 f19_stgap_6402[10];   /* gap */    /* 0x06402 */
    uint8 m_menuSelTab5[350];                /* 0x0640C */
    uint8 f19_stgap_656A[8];   /* gap */     /* 0x0656A */
    uint16 m_word_26572;                     /* 0x06572 */
    int16 m_word_26574[183];                 /* 0x06574 */
    uint8 m_menuSelTab6[300];                /* 0x066E2 */
    uint8 f19_stgap_680E[16];   /* gap */    /* 0x0680E */
    uint16 m_word_2681E;                     /* 0x0681E */
    uint16 m_word_26820[1199];               /* 0x06820 */
    uint16 m_namePtrTab[1011];               /* 0x0717E */
    char m_str7964[44];                      /* 0x07964 */
    int16 m_word_27990[4];                   /* 0x07990 */
    int16 m_word_27998[463];                 /* 0x07998 */
    uint8 f19_stgap_7D36[1];   /* gap */     /* 0x07D36 */
    uint8 m_byte_27D37[16];                  /* 0x07D37 */
    uint8 m_byte_27D47[16];                  /* 0x07D47 */
    uint8 m_byte_27D57[16];                  /* 0x07D57 */
    uint8 m_byte_27D67[7013];                /* 0x07D67 */
    char m_bufCoordStr[88];                  /* 0x098CC */
    int16 m_selAvailTab[21];                 /* 0x09924 */
    uint8 m_gridBuf5[518];                   /* 0x0994E */
    uint8 m_gridBuf4[512];                   /* 0x09B54 */
    uint8 m_word_29D54[1368];                /* 0x09D54 */
    uint8 f19_stgap_A2AC[26];   /* gap */    /* 0x0A2AC */
    uint8 m_gridBuf3[514];                   /* 0x0A2C6 */
    uint8 m_gridBuf2[256];                   /* 0x0A4C8 */
    uint8 m_terrainTileBlock[3500];          /* 0x0A5C8 */
    uint8 m_gridBuf1[26];                    /* 0x0B374 */
    uint8 m_f19_worldObjects[2];             /* 0x0B38E */
    uint8 m_f19_worldObjects_B390[4];        /* 0x0B390 */
    int16 m_word_2B394[4];                   /* 0x0B394 */
    uint8 m_siteObjData[1190];               /* 0x0B39C */
    uint8 m_terrainGrid[260];                /* 0x0B842 */
    uint8 m_f19_targets[18];                 /* 0x0B946 */
    uint8 f19_stgap_B958[18];   /* gap */    /* 0x0B958 */
    char m_strB96A[526];                     /* 0x0B96A */
    uint8 m_f19_flightUnits[1514];           /* 0x0BB78 */
    uint8 m_objectTypeTable[1654];           /* 0x0C162 */
    int16 m_word_2C7D8[209];                 /* 0x0C7D8 */
    uint8 m_wldReadBuf8[104];                /* 0x0C97A */
    uint8 m_wldReadBuf7[112];                /* 0x0C9E2 */
    uint8 m_wldReadBuf1[30];                 /* 0x0CA52 */
    int16 m_wldOffsets[100];                 /* 0x0CA70 */
    int8 m_wldReadBuf11[752];                /* 0x0CB38 */
    uint8 m_terrainTilePtrs[1088];           /* 0x0CE28 */
    uint8 f19_stgap_D268[6];   /* gap */     /* 0x0D268 */
    int16 m_word_2D26E;                      /* 0x0D26E */
    int16 m_word_2D270;                      /* 0x0D270 */
    int16 m_word_2D272;                      /* 0x0D272 */
    int16 m_seg_2D274;                       /* 0x0D274 */
    uint16 m_word_2D276;                     /* 0x0D276 */
    uint8 m_objectActive[88];                /* 0x0D278 */
    int16 m_typeIdxTab[256];                 /* 0x0D2D0 */
    uint8 f19_stgap_D4D0[11056];   /* gap */ /* 0x0D4D0 */
};
#pragma pack(pop)

extern struct F19STData f19_stSpace;

#define word_200E6 (*(int16 *)&f19_stSpace.m_word_200E6)
#define typeNameTab f19_stSpace.m_typeNameTab
#define str282 f19_stSpace.m_str282
#define statT1 f19_stSpace.m_statT1
#define esTable f19_stSpace.m_esTable
#define byte_212C2 f19_stSpace.m_byte_212C2
#define word_21718 f19_stSpace.m_word_21718
#define clipTable ((struct ClipEntry *)f19_stSpace.m_clipTable)
#define g_flagTable2CFE f19_stSpace.m_g_flagTable2CFE
#define strTab14 f19_stSpace.m_strTab14
#define strTab32 f19_stSpace.m_strTab32
#define siteTypeParms f19_stSpace.m_siteTypeParms
#define f19_linkTab ((struct LinkPair *)f19_stSpace.m_f19_linkTab)
#define missionSpeedTab f19_stSpace.m_missionSpeedTab
#define loadoutTab f19_stSpace.m_loadoutTab
#define f19_siteParms ((struct SiteParm *)f19_stSpace.m_f19_siteParms)
#define briefTimeA f19_stSpace.m_briefTimeA
#define briefTimeB f19_stSpace.m_briefTimeB
#define briefTimeC f19_stSpace.m_briefTimeC
#define briefCoord2 f19_stSpace.m_briefCoord2
#define word_2542C f19_stSpace.m_word_2542C
#define word_25454 f19_stSpace.m_word_25454
#define word_2547C f19_stSpace.m_word_2547C
#define word_25480 f19_stSpace.m_word_25480
#define word_25722 f19_stSpace.m_word_25722
#define word_2591A (*(int16 *)&f19_stSpace.m_word_2591A)
#define word_2591C f19_stSpace.m_word_2591C
#define word_2592A f19_stSpace.m_word_2592A
#define word_25B46 f19_stSpace.m_word_25B46
#define selInitTab f19_stSpace.m_selInitTab
#define menuSelTab ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab)
#define menuSelTab2 ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab2)
#define word_2607A (*(uint16 *)&f19_stSpace.m_word_2607A)
#define word_26092 (*(uint16 *)&f19_stSpace.m_word_26092)
#define initTab2 f19_stSpace.m_initTab2
#define menuSelTab3 ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab3)
#define menuSelTab4 ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab4)
#define menuSelTab5 ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab5)
#define word_26572 (*(uint16 *)&f19_stSpace.m_word_26572)
#define word_26574 f19_stSpace.m_word_26574
#define menuSelTab6 ((struct MenuSelBlk *)f19_stSpace.m_menuSelTab6)
#define word_2681E (*(uint16 *)&f19_stSpace.m_word_2681E)
#define word_26820 f19_stSpace.m_word_26820
#define namePtrTab f19_stSpace.m_namePtrTab
#define str7964 f19_stSpace.m_str7964
#define word_27990 f19_stSpace.m_word_27990
#define word_27998 f19_stSpace.m_word_27998
#define byte_27D37 f19_stSpace.m_byte_27D37
#define byte_27D47 f19_stSpace.m_byte_27D47
#define byte_27D57 f19_stSpace.m_byte_27D57
#define byte_27D67 f19_stSpace.m_byte_27D67
#define selAvailTab f19_stSpace.m_selAvailTab
#define word_29D54 ((struct MsnRec *)f19_stSpace.m_word_29D54)
#define word_2B394 f19_stSpace.m_word_2B394
#define siteObjData f19_stSpace.m_siteObjData
#define strB96A f19_stSpace.m_strB96A
#define f19_flightUnits ((FlightUnit *)f19_stSpace.m_f19_flightUnits)
#define word_2C7D8 f19_stSpace.m_word_2C7D8
#define word_2D26E (*(int16 *)&f19_stSpace.m_word_2D26E)
#define word_2D270 (*(int16 *)&f19_stSpace.m_word_2D270)
#define word_2D272 (*(int16 *)&f19_stSpace.m_word_2D272)
#define seg_2D274 (*(int16 *)&f19_stSpace.m_seg_2D274)
#define word_2D276 (*(uint16 *)&f19_stSpace.m_word_2D276)
#define typeIdxTab f19_stSpace.m_typeIdxTab
#define statT2 ((int16 *)f19_stSpace.m_statT1)
#define statT3 ((int16 *)f19_stSpace.m_statT1)
#define statT4 ((int16 *)f19_stSpace.m_statT1)
#define byte_22326 ((int8 *)f19_stSpace.m_clipTable)
#define word_23E26 ((struct Attr14 *)((uint8 *)f19_stSpace.m_strTab14 + 8))
#define ringTypes ((RingType *)((uint8 *)f19_stSpace.m_strTab14 + 8))
#define unitNameTab ((char (*)[32])((uint8 *)f19_stSpace.m_strTab32 + 0))
#define word_241C8 ((struct Rec18 *)f19_stSpace.m_siteTypeParms)
#define word_2B38E ((struct ObjD *)f19_stSpace.m_f19_worldObjects)
#define siteNameData ((uint8 *)f19_stSpace.m_f19_worldObjects)
#define tileMarkMap ((int8 *)f19_stSpace.m_terrainGrid)
#define scrStr ((char *)f19_stSpace.m_strB96A)
#define scrStrBuf ((char *)f19_stSpace.m_strB96A)
#define word_2CA70 ((int16 *)f19_stSpace.m_wldOffsets)
#define wldNameTab ((uint16 *)f19_stSpace.m_wldOffsets)
#define sprParmsTab ((int8 *)f19_dsegAt(0x0))
#define byte_20A1A (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 40))
#define g_cntA (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 40))
#define g_cntB (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 40))
#define g_cntC (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 40))
#define g_cntD (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 40))
#define byte_20A1B (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 41))
#define blinkTimer (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 42))
#define byte_20A1D (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 43))
/* drawLine/clipper cells (START dseg): clipMaxX=0xD25 clipMaxY=0xD27,
 * lineX0=0xD2B lineX1=0xD2D lineY0=0xD2F lineY1=0xD31 — verified vs
 * lst/start_en_ada.lst drawLine (sub_1C083) store order. */
#define g_clipMaxX (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 819))
#define g_clipMaxY (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 821))
#define g_lineX0 (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 825))
#define g_lineX1 (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 827))
#define g_lineY0 (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 829))
#define g_lineY1 (*(int16 *)((uint8 *)f19_stSpace.m_esTable + 831))
#define byte_212BA (*(uint8 *)((uint8 *)f19_stSpace.m_esTable + 2248))
#define byte_216AA (*(uint8 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1000))
#define byte_216AB (*(uint8 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1001))
#define word_216CA (*(int16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1032))
#define word_216D6 (*(int16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1044))
#define word_21706 (*(uint16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1092))
#define word_21708 (*(uint16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1094))
#define word_2170A (*(uint16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1096))
#define word_2170C (*(uint16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1098))
#define word_21712 (*(int16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1104))
#define word_21714 (*(int16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1106))
#define word_21716 (*(int16 *)((uint8 *)f19_stSpace.m_byte_212C2 + 1108))
#define byte_22318 (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3072))
#define byte_22319 (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3073))
#define byte_2231A (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3074))
#define byte_2231B (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3075))
#define byte_2231C (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3076))
#define byte_2231D (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3077))
#define byte_2231E (*(uint8 *)((uint8 *)f19_stSpace.m_word_21718 + 3078))
#define word_22320 (*(uint16 *)((uint8 *)f19_stSpace.m_word_21718 + 3080))
#define word_22324 (*(int16 *)((uint8 *)f19_stSpace.m_word_21718 + 3084))
#define word_2367C (*(int16 *)((uint8 *)f19_stSpace.m_g_flagTable2CFE + 2430))
#define clipEntryCount (*(int16 *)((uint8 *)f19_stSpace.m_g_flagTable2CFE + 2430))
#define word_2367E (*(int16 *)((uint8 *)f19_stSpace.m_g_flagTable2CFE + 2432))
#define word_23680 (*(int16 *)((uint8 *)f19_stSpace.m_g_flagTable2CFE + 2434))
#define rtcFlagByte (*(int8 *)((uint8 *)f19_stSpace.m_strTab14 + 1))
#define rtcTickBuf (*(int16 *)((uint8 *)f19_stSpace.m_strTab14 + 6))
#define word_23E28 (*(int16 *)((uint8 *)f19_stSpace.m_strTab14 + 10))
#define missionTimeFlag (*(int16 *)((uint8 *)f19_stSpace.m_f19_linkTab + 102))
#define word_24FFC (*(uint16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 564))
#define word_25014 (*(uint16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 588))
#define word_25016 (*(int16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 590))
#define word_25034 (*(int16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 620))
#define word_25064 (*(int16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 668))
#define word_2542A (*(uint16 *)((uint8 *)f19_stSpace.m_briefCoord2 + 1634))
#define word_256E2 (*(int16 *)((uint8 *)f19_stSpace.m_word_25480 + 610))
#define word_256FA (*(int16 *)((uint8 *)f19_stSpace.m_word_25480 + 634))
#define word_256FC (*(int16 *)((uint8 *)f19_stSpace.m_word_25480 + 636))
#define word_25B2C (*(uint16 *)((uint8 *)f19_stSpace.m_blinkColors + 508))
#define word_25B44 (*(uint16 *)((uint8 *)f19_stSpace.m_blinkColors + 532))
#define word_25B64 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 30))
#define word_25B84 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 62))
#define word_25BA4 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 94))
#define word_25BC4 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 126))
#define word_25BE4 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 158))
#define word_25C04 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 190))
#define word_25C24 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 222))
#define word_25C44 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 254))
#define word_25C64 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 286))
#define word_25C84 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 318))
#define word_25CE6 (*(int16 *)((uint8 *)f19_stSpace.m_word_25B46 + 416))
#define word_25CF6 (*(uint16 *)((uint8 *)f19_stSpace.m_word_25B46 + 432))
#define word_25D30 (*(uint16 *)((uint8 *)f19_stSpace.m_word_25B46 + 490))
#define word_25D48 (*(uint16 *)((uint8 *)f19_stSpace.m_word_25B46 + 514))
#define word_25F7C (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab + 216))
#define word_25F94 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab + 240))
#define word_25FAC (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab + 264))
#define word_26050 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab2 + 116))
#define word_262A8 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab3 + 166))
#define word_262C0 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab3 + 190))
#define word_262D8 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab3 + 214))
#define word_263AE (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab4 + 166))
#define word_263C6 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab4 + 190))
#define word_26480 (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 116))
#define word_2655A (*(uint16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 334))
#define word_26592 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 30))
#define word_265B2 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 62))
#define word_265B6 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 66))
#define siteSprOff1 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 94))
#define siteSprOff2 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 94))
#define word_265D6 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 98))
#define unitSprOff (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 158))
#define gridSprOff (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 158))
#define word_26676 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 258))
#define word_26696 (*(int16 *)((uint8 *)f19_stSpace.m_word_26574 + 290))
#define titleParms (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 416))
#define briefParms (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 440))
#define word_26E3C (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 1564))
#define word_26E54 (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 1588))
#define word_26F1A (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 1786))
#define word_26F2A (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 1802))
#define word_27094 (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 2164))
#define word_270AC (*(int16 *)((uint8 *)f19_stSpace.m_word_26820 + 2188))
#define objParms ((struct ObjF04 *)f19_dsegAt(*(uint16 *)f19_dsegAt(0x70AC)))
#define word_277EE (*(int16 *)((uint8 *)f19_stSpace.m_namePtrTab + 1648))
#define word_278C6 (*(int16 *)((uint8 *)f19_stSpace.m_namePtrTab + 1864))
#define word_278D4 (*(int16 *)((uint8 *)f19_stSpace.m_namePtrTab + 1878))
#define word_27B3A (*(int16 *)((uint8 *)f19_stSpace.m_word_27998 + 418))
#define word_27E50 (*(uint16 *)((uint8 *)f19_stSpace.m_byte_27D67 + 233))
#define byte_27E52 (*(uint8 *)((uint8 *)f19_stSpace.m_byte_27D67 + 235))
#define word_27E54 (*(uint16 *)((uint8 *)f19_stSpace.m_byte_27D67 + 237))
#define word_27E56 (*(int16 *)((uint8 *)f19_stSpace.m_byte_27D67 + 239))
#define byte_27E58 (*(uint8 *)((uint8 *)f19_stSpace.m_byte_27D67 + 241))
#define byte_27E59 (*(uint8 *)((uint8 *)f19_stSpace.m_byte_27D67 + 242))
#define byte_27E5A (*(uint8 *)((uint8 *)f19_stSpace.m_byte_27D67 + 243))
#define word_298D2 (*(int16 *)((uint8 *)f19_stSpace.m_bufCoordStr + 6))
#define word_298D4 (*(int16 *)((uint8 *)f19_stSpace.m_bufCoordStr + 8))
#define word_298E0 (*(int16 *)((uint8 *)f19_stSpace.m_bufCoordStr + 20))
#define word_298E6 (*(int16 *)((uint8 *)f19_stSpace.m_bufCoordStr + 26))
#define unitMarksOn (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 28))
#define byte_298E9 (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 29))
#define byte_298F0 (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 36))
#define byte_298F6 (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 42))
#define byte_298F7 (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 43))
#define rtcTickSaved (*(int16 *)((uint8 *)f19_stSpace.m_bufCoordStr + 84))
#define ringMode (*(uint8 *)((uint8 *)f19_stSpace.m_bufCoordStr + 86))
#define tileMarksOn (*(uint8 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 720))  /* dseg:0xBE48 */
/* map clip window (init image: X1=8 Y1=10 X2=232 Y2=178 — the 224x168
 * theater-map viewport; original cells at 0x653C/0x653E/0x6540/0x6542) */
#define mapClipX1 (*(int16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 0x130))
#define mapClipY1 (*(int16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 0x132))
#define mapClipX2 (*(int16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 0x134))
#define mapClipY2 (*(int16 *)((uint8 *)f19_stSpace.m_menuSelTab5 + 0x136))
#define word_29948 (*(int16 *)((uint8 *)f19_stSpace.m_selAvailTab + 36))
#define flag_29948 (*(int16 *)((uint8 *)f19_stSpace.m_selAvailTab + 36))
#define byte_29B50 (*(uint8 *)((uint8 *)f19_stSpace.m_gridBuf5 + 514))
#define word_29B52 (*(uint16 *)((uint8 *)f19_stSpace.m_gridBuf5 + 516))
#define hallfameCount (*(int16 *)((uint8 *)f19_stSpace.m_gridBuf5 + 516))
#define word_2A0C4 (*(int16 *)((uint8 *)f19_stSpace.m_word_29D54 + 880))
#define byte_2B384 (*(uint8 *)((uint8 *)f19_stSpace.m_gridBuf1 + 16))
#define word_2B386 (*(uint16 *)((uint8 *)f19_stSpace.m_gridBuf1 + 18))
#define word_2B38A (*(int16 *)((uint8 *)f19_stSpace.m_gridBuf1 + 22))
#define word_2B83E (*(int16 *)((uint8 *)f19_stSpace.m_siteObjData + 1186))
#define g_gfxModeNum (*(int16 *)((uint8 *)f19_stSpace.m_siteObjData + 1186))
#define drawModeSel (*(uint8 *)((uint8 *)f19_stSpace.m_siteObjData + 1186))
#define word_2B948 (*(int16 *)((uint8 *)f19_stSpace.m_f19_targets + 2))
#define pathWpA (*(int16 *)((uint8 *)f19_stSpace.m_f19_targets + 4))
#define word_2B94E (*(int16 *)((uint8 *)f19_stSpace.m_f19_targets + 8))
#define word_2B95A (*(int16 *)f19_dsegAt(0xB95A))
#define escortObj (*(int16 *)((uint8 *)f19_stSpace.m_strB96A + 520))
#define briefDepartSite (*(int16 *)((uint8 *)f19_stSpace.m_strB96A + 520))
#define word_2BB74 (*(int16 *)((uint8 *)f19_stSpace.m_strB96A + 522))
#define rtcEnabled (*(int16 *)((uint8 *)f19_stSpace.m_strB96A + 522))
#define esTabBase (*(uint16 *)((uint8 *)f19_stSpace.m_strB96A + 524))
#define briefPatrolType (*(int16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 22))
#define word_2BE4A (*(int16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 722))
#define word_2BE4C (*(int16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 724))
#define byte_2BE4E (*(uint8 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 726))
#define word_2BE50 (*(uint16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 728))
#define word_2C144 (*(int16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1484))
#define selCursor (*(int16 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1484))
#define tgtPreciseX (*(int32 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1486))
#define tgtPreciseY (*(int32 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1486))
#define byte_2C160 (*(uint8 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1512))
#define gamePhase (*(int8 *)((uint8 *)f19_stSpace.m_f19_flightUnits + 1512))
#define selRowIdx (*(int16 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1642))
#define word_2C7CE (*(int16 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1644))
#define flag2C7CE (*(int16 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1644))
#define word_2C7D2 (*(int16 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1648))
#define word_2C7D4 (*(int16 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1650))
#define byte_2C7D6 (*(uint8 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1652))
#define byte_2C7D7 (*(uint8 *)((uint8 *)f19_stSpace.m_objectTypeTable + 1653))
#define word_2C968 (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 400))
#define objCursor (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 400))
#define byte_2C970 (*(uint8 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 408))
#define word_2C972 (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 410))
#define word_2C974 (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 412))
#define byte_2C976 (*(uint8 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 414))
#define byte_2C977 (*(uint8 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 415))
#define siteMarksOn (*(uint8 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 415))
#define objectCount (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 416))
#define siteMarkCount (*(int16 *)((uint8 *)f19_stSpace.m_word_2C7D8 + 416))
#define word_2C9E0 (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf8 + 102))
#define word_2C9E0_CELL ((uint8 *)f19_stSpace.m_wldReadBuf8 + 102)
#define byte_2C9E0 (*(uint8 *)((uint8 *)f19_stSpace.m_wldReadBuf8 + 102))
#define word_2CA48 (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 102))
#define briefTab (*(uint16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 102))
#define word_2CA4C (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 106))
#define flag2CA4C (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 106))
#define word_2CA4E (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 108))
#define viewOriginX (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 108))
#define word_2CA50 (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 110))
#define viewOriginY (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf7 + 110))
#define word_2CA60 (*(uint16 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 14))
#define byte_2CA62 (*(uint8 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 16))
#define briefActive (*(uint8 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 16))
#define word_2CA64 (*(uint16 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 18))
#define byte_2CA6A (*(uint8 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 24))
#define word_2CA6C (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 26))
#define briefPage (*(int16 *)((uint8 *)f19_stSpace.m_wldReadBuf1 + 26))
#define byte_2CE26 (*(uint8 *)((uint8 *)f19_stSpace.m_wldReadBuf11 + 750))
#define word_2D05A (*(int16 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 562))
#define word_2D05C (*(int16 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 564))
#define byte_2D060 (*(uint8 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 568))
#define word_2D064 (*(int16 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 572))
#define byte_2D06A (*(uint8 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 578))
#define byte_2D06B (*(uint8 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 579))
#define word_2D06C (*(int16 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 580))
#define savedPage (*(int16 *)((uint8 *)f19_stSpace.m_terrainTilePtrs + 580))
#define word_2D2C4 (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 76))
#define word_2D2C6 (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 78))
#define word_2D2C8 (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 80))
#define word_2D2CA (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 82))
#define word_2D2CC (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 84))
#define word_2D2CE (*(int16 *)((uint8 *)f19_stSpace.m_objectActive + 86))
#define word_2D2F4 (*(int16 *)((uint8 *)f19_stSpace.m_typeIdxTab + 36))
#define word_2D2F6 (*(int16 *)((uint8 *)f19_stSpace.m_typeIdxTab + 38))
#define word_2D2F8 (*(int16 *)((uint8 *)f19_stSpace.m_typeIdxTab + 40))

void f19_stVarsReset(void);
#endif
