/* generated by tools/f19_deblob.py - real globals replacing the
   f19_dseg offset macros (START.EXE data segment). */
#ifndef F19STVARS_H
#define F19STVARS_H
#include "inttype.h"
#include "f19seg.h"

extern int16 word_200E6;
extern uint16 typeNameTab[22];
extern char str282[1076];
extern int16 statT1[414];
extern uint32 esTable[564];
extern int8 byte_212C2[1110];
extern int16 word_21718[1543];
struct ClipEntry;
extern struct ClipEntry clipTable[27];
extern uint8 g_flagTable2CFE[3766];
extern int16 gridLevelSize[6];
extern uint16 f19d_terrainBuf1[5];
struct TerrainPtrTable;
extern struct TerrainPtrTable f19d_terrainTileCounts[9];
extern uint16 f19d_missionMidX[10];
extern char strTab14[1][14];
extern char strTab32[1][32];
extern int16 siteTypeParms[347];
struct LinkPair;
extern struct LinkPair f19_linkTab[34];
extern int16 missionSpeedTab[248];
extern uint8 loadoutTab[1046];
struct SiteParm;
extern struct SiteParm f19_siteParms[56];
extern uint16 f19d_regnPlhPtr;
extern uint16 f19d_plhFiles[4];
extern char briefTimeA[6];
extern char briefTimeB[6];
extern char briefTimeC[6];
extern char briefCoord2[1636];
extern int16 word_2542C[20];
extern uint16 word_25454[20];
extern int16 word_2547C[2];
extern int16 word_25480[337];
extern int16 word_25722[10][25];
extern int16 word_2591A;
extern uint16 word_2591C[7];
extern uint16 word_2592A[3];
extern int16 blinkColors[267];
extern int16 word_25B46[258];
extern int16 selInitTab[173];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab[6];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab2[3];
extern uint16 word_2607A;
extern uint16 word_26092;
extern int16 initTab2[183];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab3[5];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab4[5];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab5[7];
extern uint16 word_26572;
extern int16 word_26574[183];
struct MenuSelBlk;
extern struct MenuSelBlk menuSelTab6[6];
extern uint16 word_2681E;
extern uint16 word_26820[1199];
extern uint16 namePtrTab[1011];
extern char str7964[44];
extern int16 word_27990[4];
extern int16 word_27998[463];
extern uint8 byte_27D37[16];
extern uint8 byte_27D47[16];
extern uint8 byte_27D57[16];
extern uint8 byte_27D67[7013];
extern char f19d_bufCoordStr[88];
extern int16 selAvailTab[21];
extern uint8 f19d_gridBuf5[518];
extern uint8 f19d_gridBuf4[512];
struct MsnRec;
extern struct MsnRec word_29D54[18];
extern uint8 f19d_gridBuf3[514];
extern uint8 f19d_gridBuf2[256];
extern uint8 f19d_terrainTileBlock[3500];
extern uint8 f19d_gridBuf1[26];
extern WorldObject f19d_f19_worldObjects[2];
extern WorldObject f19d_f19_worldObjects[4];
extern int16 word_2B394[4];
extern uint8 siteObjData[1190];
extern uint8 f19d_terrainGrid[260];
struct Target;
extern struct Target f19d_f19_targets[1];
extern char strB96A[526];
extern FlightUnit f19_flightUnits[1514];
extern uint8 f19d_objectTypeTable[1654];
extern int16 word_2C7D8[209];
extern uint8 f19d_wldReadBuf8[104];
extern uint8 f19d_wldReadBuf7[112];
extern uint8 f19d_wldReadBuf1[30];
extern int16 f19d_wldOffsets[100];
extern int8 f19d_wldReadBuf11[752];
struct TerrainPtrTable;
extern struct TerrainPtrTable f19d_terrainTilePtrs[17];
extern int16 word_2D26E;
extern int16 word_2D270;
extern int16 word_2D272;
extern int16 seg_2D274;
extern uint16 word_2D276;
extern uint8 f19d_objectActive[88];
extern int16 typeIdxTab[256];
#define sprParmsTab ((int8 *)f19_dsegAt(0))
#define sprParmsTab ((int8 *)f19_dsegAt(0))
#define byte_20A1A (*(uint8 *)((uint8 *)esTable + 40))
#define g_cntA (*(uint8 *)((uint8 *)esTable + 40))
#define g_cntB (*(uint8 *)((uint8 *)esTable + 40))
#define g_cntC (*(uint8 *)((uint8 *)esTable + 40))
#define g_cntD (*(uint8 *)((uint8 *)esTable + 40))
#define byte_20A1B (*(uint8 *)((uint8 *)esTable + 41))
#define blinkTimer (*(uint8 *)((uint8 *)esTable + 42))
#define blinkTimer (*(uint8 *)((uint8 *)esTable + 42))
#define blinkTimer (*(uint8 *)((uint8 *)esTable + 42))
#define byte_20A1D (*(uint8 *)((uint8 *)esTable + 43))
#define g_lineX0 (*(int16 *)((uint8 *)esTable + 825))
#define g_lineY0 (*(int16 *)((uint8 *)esTable + 825))
#define byte_212BA (*(uint8 *)((uint8 *)esTable + 2248))
#define byte_212BA (*(uint8 *)((uint8 *)esTable + 2248))
#define byte_212BA (*(uint8 *)((uint8 *)esTable + 2248))
#define byte_216AA byte_212C2[1000]
#define byte_216AA byte_212C2[1000]
#define byte_216AB byte_212C2[1001]
#define byte_216AB byte_212C2[1001]
#define word_216CA (*(int16 *)((uint8 *)byte_212C2 + 1032))
#define word_216D6 (*(int16 *)((uint8 *)byte_212C2 + 1044))
#define word_21706 (*(uint16 *)((uint8 *)byte_212C2 + 1092))
#define word_21708 (*(uint16 *)((uint8 *)byte_212C2 + 1094))
#define word_2170A (*(uint16 *)((uint8 *)byte_212C2 + 1096))
#define word_2170A (*(uint16 *)((uint8 *)byte_212C2 + 1096))
#define word_2170C (*(uint16 *)((uint8 *)byte_212C2 + 1098))
#define word_2170C (*(uint16 *)((uint8 *)byte_212C2 + 1098))
#define word_21712 (*(int16 *)((uint8 *)byte_212C2 + 1104))
#define word_21714 (*(int16 *)((uint8 *)byte_212C2 + 1106))
#define word_21714 (*(int16 *)((uint8 *)byte_212C2 + 1106))
#define word_21716 (*(int16 *)((uint8 *)byte_212C2 + 1108))
#define byte_22318 (*(uint8 *)((uint8 *)word_21718 + 3072))
#define byte_22319 (*(uint8 *)((uint8 *)word_21718 + 3073))
#define byte_2231A (*(uint8 *)((uint8 *)word_21718 + 3074))
#define byte_2231B (*(uint8 *)((uint8 *)word_21718 + 3075))
#define byte_2231C (*(uint8 *)((uint8 *)word_21718 + 3076))
#define byte_2231D (*(uint8 *)((uint8 *)word_21718 + 3077))
#define byte_2231E (*(uint8 *)((uint8 *)word_21718 + 3078))
#define word_22320 word_21718[1540]
#define word_22324 word_21718[1542]
#define word_22324 word_21718[1542]
#define word_22324 word_21718[1542]
#define word_22324 word_21718[1542]
#define word_2367C (*(int16 *)((uint8 *)g_flagTable2CFE + 2430))
#define clipEntryCount (*(int16 *)((uint8 *)g_flagTable2CFE + 2430))
#define word_2367C (*(int16 *)((uint8 *)g_flagTable2CFE + 2430))
#define word_2367E (*(int16 *)((uint8 *)g_flagTable2CFE + 2432))
#define word_23680 (*(int16 *)((uint8 *)g_flagTable2CFE + 2434))
#define rtcFlagByte (*(int8 *)((uint8 *)strTab14 + 1))
#define rtcTickBuf (*(int16 *)((uint8 *)strTab14 + 6))
#define word_23E28 (*(int16 *)((uint8 *)strTab14 + 10))
#define word_23E28 (*(int16 *)((uint8 *)strTab14 + 10))
#define missionTimeFlag (*(int16 *)((uint8 *)f19_linkTab + 102))
#define word_24FFC (*(uint16 *)((uint8 *)briefCoord2 + 564))
#define word_25014 (*(uint16 *)((uint8 *)briefCoord2 + 588))
#define word_25016 (*(int16 *)((uint8 *)briefCoord2 + 590))
#define word_25034 (*(int16 *)((uint8 *)briefCoord2 + 620))
#define word_25064 (*(int16 *)((uint8 *)briefCoord2 + 668))
#define word_2542A (*(uint16 *)((uint8 *)briefCoord2 + 1634))
#define word_256E2 word_25480[305]
#define word_256FA word_25480[317]
#define word_256FC word_25480[318]
#define word_25B2C blinkColors[254]
#define word_25B44 blinkColors[266]
#define word_25B64 word_25B46[15]
#define word_25B84 word_25B46[31]
#define word_25BA4 word_25B46[47]
#define word_25BC4 word_25B46[63]
#define word_25BE4 word_25B46[79]
#define word_25C04 word_25B46[95]
#define word_25C24 word_25B46[111]
#define word_25C44 word_25B46[127]
#define word_25C64 word_25B46[143]
#define word_25C84 word_25B46[159]
#define word_25CE6 word_25B46[208]
#define word_25CF6 word_25B46[216]
#define word_25D30 word_25B46[245]
#define word_25D48 word_25B46[257]
#define word_25F7C (*(uint16 *)((uint8 *)menuSelTab + 216))
#define word_25F94 (*(uint16 *)((uint8 *)menuSelTab + 240))
#define word_25FAC (*(uint16 *)((uint8 *)menuSelTab + 264))
#define word_26050 (*(uint16 *)((uint8 *)menuSelTab2 + 116))
#define word_262A8 (*(uint16 *)((uint8 *)menuSelTab3 + 166))
#define word_262C0 (*(uint16 *)((uint8 *)menuSelTab3 + 190))
#define word_262D8 (*(uint16 *)((uint8 *)menuSelTab3 + 214))
#define word_263AE (*(uint16 *)((uint8 *)menuSelTab4 + 166))
#define word_263C6 (*(uint16 *)((uint8 *)menuSelTab4 + 190))
#define word_26480 (*(uint16 *)((uint8 *)menuSelTab5 + 116))
#define word_2655A (*(uint16 *)((uint8 *)menuSelTab5 + 334))
#define word_26592 word_26574[15]
#define word_265B2 word_26574[31]
#define word_265B6 word_26574[33]
#define siteSprOff1 word_26574[47]
#define siteSprOff2 word_26574[47]
#define word_265D6 word_26574[49]
#define unitSprOff word_26574[79]
#define gridSprOff word_26574[79]
#define word_26676 word_26574[129]
#define word_26696 word_26574[145]
#define titleParms word_26820[208]
#define briefParms word_26820[220]
#define word_26E3C word_26820[782]
#define word_26E54 word_26820[794]
#define word_26F1A word_26820[893]
#define word_26F2A word_26820[901]
#define word_27094 word_26820[1082]
#define word_270AC word_26820[1094]
#define objParms ((struct ObjF04 *)f19_dsegAt(*(uint16 *)f19_dsegAt(0x70AC)))
#define word_277EE namePtrTab[824]
#define word_278C6 namePtrTab[932]
#define word_278D4 namePtrTab[939]
#define word_27B3A word_27998[209]
#define word_27E50 (*(uint16 *)((uint8 *)byte_27D67 + 233))
#define byte_27E52 byte_27D67[235]
#define word_27E54 (*(uint16 *)((uint8 *)byte_27D67 + 237))
#define word_27E56 (*(int16 *)((uint8 *)byte_27D67 + 239))
#define byte_27E58 byte_27D67[241]
#define byte_27E59 byte_27D67[242]
#define byte_27E5A byte_27D67[243]
#define word_298D2 (*(int16 *)((uint8 *)f19d_bufCoordStr + 6))
#define word_298D4 (*(int16 *)((uint8 *)f19d_bufCoordStr + 8))
#define word_298E0 (*(int16 *)((uint8 *)f19d_bufCoordStr + 20))
#define word_298E0 (*(int16 *)((uint8 *)f19d_bufCoordStr + 20))
#define word_298E6 (*(int16 *)((uint8 *)f19d_bufCoordStr + 26))
#define unitMarksOn f19d_bufCoordStr[28]
#define unitMarksOn f19d_bufCoordStr[28]
#define unitMarksOn f19d_bufCoordStr[28]
#define byte_298E9 f19d_bufCoordStr[29]
#define byte_298F0 f19d_bufCoordStr[36]
#define byte_298F6 f19d_bufCoordStr[42]
#define byte_298F6 f19d_bufCoordStr[42]
#define byte_298F6 f19d_bufCoordStr[42]
#define byte_298F7 f19d_bufCoordStr[43]
#define byte_298F7 f19d_bufCoordStr[43]
#define byte_298F7 f19d_bufCoordStr[43]
#define rtcTickSaved (*(int16 *)((uint8 *)f19d_bufCoordStr + 84))
#define ringMode f19d_bufCoordStr[86]
#define ringMode f19d_bufCoordStr[86]
#define ringMode f19d_bufCoordStr[86]
#define word_29948 selAvailTab[18]
#define flag_29948 selAvailTab[18]
#define flag_29948 selAvailTab[18]
#define byte_29B50 f19d_gridBuf5[514]
#define byte_29B50 f19d_gridBuf5[514]
#define word_29B52 (*(uint16 *)((uint8 *)f19d_gridBuf5 + 516))
#define hallfameCount (*(int16 *)((uint8 *)f19d_gridBuf5 + 516))
#define word_2A0C4 (*(int16 *)((uint8 *)word_29D54 + 880))
#define word_2A0C4 (*(int16 *)((uint8 *)word_29D54 + 880))
#define word_2A0C4 (*(int16 *)((uint8 *)word_29D54 + 880))
#define byte_2B384 f19d_gridBuf1[16]
#define byte_2B384 f19d_gridBuf1[16]
#define word_2B386 (*(uint16 *)((uint8 *)f19d_gridBuf1 + 18))
#define word_2B386 (*(uint16 *)((uint8 *)f19d_gridBuf1 + 18))
#define word_2B38A (*(int16 *)((uint8 *)f19d_gridBuf1 + 22))
#define word_2B38A (*(int16 *)((uint8 *)f19d_gridBuf1 + 22))
#define word_2B38A (*(int16 *)((uint8 *)f19d_gridBuf1 + 22))
#define word_2B83E (*(int16 *)((uint8 *)siteObjData + 1186))
#define g_gfxModeNum (*(int16 *)((uint8 *)siteObjData + 1186))
#define drawModeSel siteObjData[1186]
#define word_2B948 (*(int16 *)((uint8 *)f19d_f19_targets + 2))
#define pathWpA (*(int16 *)((uint8 *)f19d_f19_targets + 4))
#define pathWpA (*(int16 *)((uint8 *)f19d_f19_targets + 4))
#define word_2B94E (*(int16 *)((uint8 *)f19d_f19_targets + 8))
#define word_2B95A f19_targets[6]
#define escortObj (*(int16 *)((uint8 *)strB96A + 520))
#define briefDepartSite (*(int16 *)((uint8 *)strB96A + 520))
#define word_2BB74 (*(int16 *)((uint8 *)strB96A + 522))
#define word_2BB74 (*(int16 *)((uint8 *)strB96A + 522))
#define rtcEnabled (*(int16 *)((uint8 *)strB96A + 522))
#define rtcEnabled (*(int16 *)((uint8 *)strB96A + 522))
#define esTabBase (*(uint16 *)((uint8 *)strB96A + 524))
#define briefPatrolType (*(int16 *)((uint8 *)f19_flightUnits + 22))
#define word_2BE4A (*(int16 *)((uint8 *)f19_flightUnits + 722))
#define word_2BE4C (*(int16 *)((uint8 *)f19_flightUnits + 724))
#define byte_2BE4E (*(uint8 *)((uint8 *)f19_flightUnits + 726))
#define word_2BE50 (*(uint16 *)((uint8 *)f19_flightUnits + 728))
#define word_2C144 (*(int16 *)((uint8 *)f19_flightUnits + 1484))
#define word_2C144 (*(int16 *)((uint8 *)f19_flightUnits + 1484))
#define word_2C144 (*(int16 *)((uint8 *)f19_flightUnits + 1484))
#define selCursor (*(int16 *)((uint8 *)f19_flightUnits + 1484))
#define tgtPreciseX (*(int32 *)((uint8 *)f19_flightUnits + 1486))
#define tgtPreciseY (*(int32 *)((uint8 *)f19_flightUnits + 1486))
#define byte_2C160 (*(uint8 *)((uint8 *)f19_flightUnits + 1512))
#define byte_2C160 (*(uint8 *)((uint8 *)f19_flightUnits + 1512))
#define byte_2C160 (*(uint8 *)((uint8 *)f19_flightUnits + 1512))
#define gamePhase (*(int8 *)((uint8 *)f19_flightUnits + 1512))
#define selRowIdx (*(int16 *)((uint8 *)f19d_objectTypeTable + 1642))
#define word_2C7CE (*(int16 *)((uint8 *)f19d_objectTypeTable + 1644))
#define flag2C7CE (*(int16 *)((uint8 *)f19d_objectTypeTable + 1644))
#define word_2C7D2 (*(int16 *)((uint8 *)f19d_objectTypeTable + 1648))
#define word_2C7D4 (*(int16 *)((uint8 *)f19d_objectTypeTable + 1650))
#define word_2C7D4 (*(int16 *)((uint8 *)f19d_objectTypeTable + 1650))
#define word_2C7D4 (*(int16 *)((uint8 *)f19d_objectTypeTable + 1650))
#define byte_2C7D6 f19d_objectTypeTable[1652]
#define byte_2C7D6 f19d_objectTypeTable[1652]
#define byte_2C7D7 f19d_objectTypeTable[1653]
#define byte_2C7D7 f19d_objectTypeTable[1653]
#define word_2C968 word_2C7D8[200]
#define word_2C968 word_2C7D8[200]
#define word_2C968 word_2C7D8[200]
#define objCursor word_2C7D8[200]
#define byte_2C970 (*(uint8 *)((uint8 *)word_2C7D8 + 408))
#define word_2C972 word_2C7D8[205]
#define word_2C972 word_2C7D8[205]
#define word_2C972 word_2C7D8[205]
#define word_2C974 word_2C7D8[206]
#define word_2C974 word_2C7D8[206]
#define word_2C974 word_2C7D8[206]
#define byte_2C976 (*(uint8 *)((uint8 *)word_2C7D8 + 414))
#define byte_2C976 (*(uint8 *)((uint8 *)word_2C7D8 + 414))
#define byte_2C977 (*(uint8 *)((uint8 *)word_2C7D8 + 415))
#define byte_2C977 (*(uint8 *)((uint8 *)word_2C7D8 + 415))
#define siteMarksOn (*(uint8 *)((uint8 *)word_2C7D8 + 415))
#define objectCount word_2C7D8[208]
#define objectCount word_2C7D8[208]
#define objectCount word_2C7D8[208]
#define siteMarkCount word_2C7D8[208]
#define word_2C9E0 (*(int16 *)((uint8 *)f19d_wldReadBuf8 + 102))
#define word_2C9E0_CELL ((uint8 *)f19d_wldReadBuf8 + 102)
#define byte_2C9E0 f19d_wldReadBuf8[102]
#define word_2CA48 (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 102))
#define word_2CA48 (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 102))
#define briefTab (*(uint16 *)((uint8 *)f19d_wldReadBuf7 + 102))
#define word_2CA4C (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 106))
#define flag2CA4C (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 106))
#define word_2CA4E (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 108))
#define word_2CA4E (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 108))
#define viewOriginX (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 108))
#define word_2CA50 (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 110))
#define word_2CA50 (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 110))
#define viewOriginY (*(int16 *)((uint8 *)f19d_wldReadBuf7 + 110))
#define word_2CA60 (*(uint16 *)((uint8 *)f19d_wldReadBuf1 + 14))
#define byte_2CA62 f19d_wldReadBuf1[16]
#define briefActive f19d_wldReadBuf1[16]
#define word_2CA64 (*(uint16 *)((uint8 *)f19d_wldReadBuf1 + 18))
#define byte_2CA6A f19d_wldReadBuf1[24]
#define byte_2CA6A f19d_wldReadBuf1[24]
#define byte_2CA6A f19d_wldReadBuf1[24]
#define word_2CA6C (*(int16 *)((uint8 *)f19d_wldReadBuf1 + 26))
#define briefPage (*(int16 *)((uint8 *)f19d_wldReadBuf1 + 26))
#define byte_2CE26 f19d_wldReadBuf11[750]
#define byte_2CE26 f19d_wldReadBuf11[750]
#define word_2D05A (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 562))
#define word_2D05C (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 564))
#define byte_2D060 (*(uint8 *)((uint8 *)f19d_terrainTilePtrs + 568))
#define word_2D064 (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 572))
#define word_2D064 (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 572))
#define word_2D064 (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 572))
#define byte_2D06A (*(uint8 *)((uint8 *)f19d_terrainTilePtrs + 578))
#define byte_2D06A (*(uint8 *)((uint8 *)f19d_terrainTilePtrs + 578))
#define byte_2D06B (*(uint8 *)((uint8 *)f19d_terrainTilePtrs + 579))
#define byte_2D06B (*(uint8 *)((uint8 *)f19d_terrainTilePtrs + 579))
#define word_2D06C (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 580))
#define word_2D06C (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 580))
#define word_2D06C (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 580))
#define savedPage (*(int16 *)((uint8 *)f19d_terrainTilePtrs + 580))
#define word_2D26E (*(int16 *)&word_2D26E)
#define word_2D26E (*(int16 *)&word_2D26E)
#define word_2D270 (*(int16 *)&word_2D270)
#define word_2D272 (*(int16 *)&word_2D272)
#define word_2D272 (*(int16 *)&word_2D272)
#define word_2D2C4 (*(int16 *)((uint8 *)f19d_objectActive + 76))
#define word_2D2C4 (*(int16 *)((uint8 *)f19d_objectActive + 76))
#define word_2D2C6 (*(int16 *)((uint8 *)f19d_objectActive + 78))
#define word_2D2C6 (*(int16 *)((uint8 *)f19d_objectActive + 78))
#define word_2D2C6 (*(int16 *)((uint8 *)f19d_objectActive + 78))
#define word_2D2C8 (*(int16 *)((uint8 *)f19d_objectActive + 80))
#define word_2D2C8 (*(int16 *)((uint8 *)f19d_objectActive + 80))
#define word_2D2CA (*(int16 *)((uint8 *)f19d_objectActive + 82))
#define word_2D2CA (*(int16 *)((uint8 *)f19d_objectActive + 82))
#define word_2D2CA (*(int16 *)((uint8 *)f19d_objectActive + 82))
#define word_2D2CC (*(int16 *)((uint8 *)f19d_objectActive + 84))
#define word_2D2CC (*(int16 *)((uint8 *)f19d_objectActive + 84))
#define word_2D2CC (*(int16 *)((uint8 *)f19d_objectActive + 84))
#define word_2D2CE (*(int16 *)((uint8 *)f19d_objectActive + 86))
#define word_2D2CE (*(int16 *)((uint8 *)f19d_objectActive + 86))
#define word_2D2F4 typeIdxTab[18]
#define word_2D2F6 typeIdxTab[19]
#define word_2D2F8 typeIdxTab[20]
#define ringTypes ((RingType *)((uint8 *)strTab14 + 8))
#define word_23E26 ((struct Attr14 *)((uint8 *)strTab14 + 8))
#define word_23E26 ((struct Attr14 *)((uint8 *)strTab14 + 8))
#define ringTypes ((RingType *)((uint8 *)strTab14 + 8))

extern const struct F19SegObj f19_stObjs[];
extern const int f19_stObjCount;
void f19_stVarsReset(void);
#endif
